# schema_registry_listener_port: 8081

schema_registry_open_file_limit: "{{open_file_limit}}"
schema_registry_jolokia_java_arg: "-javaagent:{{jolokia_jar_path}}=port={{schema_registry_jolokia_port}},host=0.0.0.0"

schema_registry_service_overrides:
  LimitNOFILE: "{{schema_registry_open_file_limit}}"
schema_registry_service_environment_overrides:
  SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  SCHEMA_REGISTRY_OPTS: "{{schema_registry_jolokia_java_arg}}"

schema_registry:
  properties:
    listeners: http://0.0.0.0:{{schema_registry_listener_port}}
    kafkastore.topic: _schemas
    debug: false
    kafkastore.ssl.endpoint.identification.algorithm: ""
