schema_registry_open_file_limit: "{{open_file_limit}}"

schema_registry_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{schema_registry_jolokia_port}},host=0.0.0.0"

schema_registry_custom_java_args: ""
schema_registry_java_args:
  - "{{ schema_registry_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

schema_registry_final_java_args: "{{ schema_registry_java_args + [ schema_registry_custom_java_args ] }}"

schema_registry_log4j_file: /etc/schema-registry/schema_registry_log4j.properties

schema_registry_service_overrides:
  LimitNOFILE: "{{schema_registry_open_file_limit}}"
schema_registry_service_environment_overrides:
  SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  SCHEMA_REGISTRY_OPTS: "{{ schema_registry_final_java_args | java_arg_build_out }}"
  SCHEMA_REGISTRY_LOG4J_OPTS: "-Dlog4j.configuration=file:{{schema_registry_log4j_file}}"

schema_registry:
  # config_file: /etc/schema-registry/schema-registry.properties
  log4j_file: "{{schema_registry_log4j_file}}"
  appender_log_path: /var/log/confluent/schema-registry/
  appender_log_name: schema-registry.log
  appender_max_log_files: 10
  appender_log_file_size: 100MB
  # systemd_file: /usr/lib/systemd/system/confluent-schema-registry.service
  # systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
  properties:
    debug: false
    kafkastore.topic: _schemas
