schema_registry_listener_port: 8081

schema_registry:
  user: cp-schema-registry
  group: confluent
  config_file: /etc/schema-registry/schema-registry.properties
  service_name: confluent-schema-registry
  systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
  properties:
    listeners: http://0.0.0.0:{{schema_registry_listener_port}}
    kafkastore.topic: _schemas
    debug: false
    kafkastore.ssl.endpoint.identification.algorithm: ""
  environment:
    SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  systemd:
    enabled: yes
    state: started
  packages:
    - "confluent-schema-registry-{{confluent.package_version}}"
    - "confluent-security-{{confluent.package_version}}"
    - "confluent-libserdes-{{confluent.package_version}}.el7"
