schema_registry_open_file_limit: "{{open_file_limit}}"

schema_registry_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{schema_registry_jolokia_port}},host=0.0.0.0"
schema_registry_jolokia_java_arg: "{{ schema_registry_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

schema_registry_service_overrides:
  LimitNOFILE: "{{schema_registry_open_file_limit}}"
schema_registry_service_environment_overrides:
  SCHEMA_REGISTRY_HEAP_OPTS: "-Xmx1000M"
  SCHEMA_REGISTRY_OPTS: "{{schema_registry_jolokia_java_arg}} -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -Djava.awt.headless=true -Xloggc:{{schema_registry_gclog_path}}{{schema_registry_gclog_name}} -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles={{schema_registry_gclog_max_log_files}} -XX:GCLogFileSize={{schema_registry_gclog_log_file_size}}"
  SCHEMA_REGISTRY_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/schema-registry/schema_registry_log4j.properties"

schema_registry_packages:
  - confluent-schema-registry
  - confluent-security

schema_registry:
  user: cp-schema-registry
  group: confluent
  config_file: /etc/schema-registry/schema-registry.properties
  log4j_file: /etc/schema-registry/schema_registry_log4j.properties
  service_name: confluent-schema-registry
  systemd_file: /usr/lib/systemd/system/confluent-schema-registry.service
  systemd_override: /etc/systemd/system/confluent-schema-registry.service.d
  properties:
    debug: false
    kafkastore.topic: _schemas
  systemd:
    enabled: yes
    state: started
