---
- name: Verify - zookeper
  hosts: zookeeper
  gather_facts: false
  tasks:
    - name: Check jolokia rest endpoint
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7770/jolokia/list"
        - "http://{{inventory_hostname}}:8079"
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - name: Check jmxexporter rest endpoint
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7771/jolokia/list"
        - "http://{{inventory_hostname}}:8080"
- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - name: Check jmxexporter rest endpoint
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7772/jolokia/list"
        - "http://{{inventory_hostname}}:8078"
- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - name: Check jmxexporter rest endpoint
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7773/jolokia/list"
        - "http://{{inventory_hostname}}:8077"
- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - name: Check jmxexporter rest endpoint
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7774/jolokia/list"
        - "http://{{inventory_hostname}}:8076"
- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - name: Check jmxexporter rest endpoint
      uri:
        url: "{{ item }}"
        status_code: 200
      with_items:
        - "http://{{inventory_hostname}}:7775/jolokia/list"
        - "http://{{inventory_hostname}}:8075"