---
- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  gather_facts: false
  tasks:
    - name: Restore the zookeeper group name
      lineinfile:
        path: "{{playbook_dir}}/molecule.yml"
        regexp: '    groups: \[ zookeeper_ccloud \]'
        line: '    groups: [ zookeeper ]'
      delegate_to: 127.0.0.1
      run_once: true

    - name: Restore the kafka_broker group name
      lineinfile:
        path: "{{playbook_dir}}/molecule.yml"
        regexp: '    groups: \[ kafka_broker_ccloud \]'
        line: '    groups: [ kafka_broker ]'
      delegate_to: 127.0.0.1
      run_once: true

    # - name: Restore the zookeeper group name
    #   lineinfile:
    #     path: "{{inventory_dir}}/ansible_inventory.yml"
    #     regexp: 'zookeeper_ccloud:'
    #     line: 'zookeeper:'
    #   delegate_to: 127.0.0.1
    #   run_once: true
    #
    # - name: Restore the kafka_broker group name
    #   lineinfile:
    #     path: "{{inventory_dir}}/ansible_inventory.yml"
    #     regexp: 'kafka_broker_ccloud:'
    #     line: 'kafka_broker:'
    #   delegate_to: 127.0.0.1
    #   run_once: true
