---
- name: Remove the Zookeeper and Kafka Broker Groups from Inventory
  hosts: zookeeper:kafka_broker
  gather_facts: false
  tasks:
    - name: Change the zookeeper group name in inventory file
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: 'zookeeper:'
        line: 'zookeeper_ccloud:'
      delegate_to: 127.0.0.1
      run_once: true

    - name: Change the kafka_broker group name in inventory file
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: 'kafka_broker:'
        line: 'kafka_broker_ccloud:'
      delegate_to: 127.0.0.1
      run_once: true

    - name: Refresh Inventory- removing the zookeeper/kafka_broker groups
      meta: refresh_inventory

    - debug: var=inventory_hostname

- name: Converge
  import_playbook: ../../../../all.yml
