confluent_common:
  repository:
    debian:
      key_url: "https://packages.confluent.io/deb/{{confluent.repo_version}}/archive.key"
      repository: "deb [arch=amd64] https://packages.confluent.io/deb/{{confluent.repo_version}} stable main"
    redhat:
      main:
        baseurl: "https://packages.confluent.io/rpm/{{confluent.repo_version}}"
        gpgcheck: 1
        gpgkey: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/archive.key"
        enabled: 1
      dist:
        baseurl: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/7"
        gpgcheck: 1
        gpgkey: "https://packages.confluent.io/rpm/{{confluent.repo_version}}/archive.key"
        enabled: 1
