confluent:
  package_name: confluent-platform-2.12
  repository:
    debian:
      key_url: https://packages.confluent.io/deb/5.3/archive.key
      repository: "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/5.3
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/5.3/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/5.3/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/5.3/archive.key
        enabled: 1
