---
### Base URL for Confluent's RPM and Debian Package Repositories
confluent_common_repository_baseurl: "https://packages.confluent.io"

confluent_common_repository_debian_baseurl: "{{confluent_common_repository_baseurl}}/deb"
confluent_common_repository_debian_key_url: "{{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_debian_repository: "deb [arch=amd64] {{confluent_common_repository_debian_baseurl}}/{{confluent_repo_version}} stable main"

confluent_common_repository_redhat_baseurl: "{{confluent_common_repository_baseurl}}/rpm"
confluent_common_repository_redhat_main_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}"
confluent_common_repository_redhat_main_gpgcheck: 1
confluent_common_repository_redhat_main_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_main_enabled: 1

confluent_common_repository_redhat_dist_baseurl: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/7"
confluent_common_repository_redhat_dist_gpgcheck: 1
confluent_common_repository_redhat_dist_gpgkey: "{{confluent_common_repository_redhat_baseurl}}/{{confluent_repo_version}}/archive.key"
confluent_common_repository_redhat_dist_enabled: 1

### Boolean to have cp-ansible install Java on hosts
install_java: true

### Java Package to install on RHEL/Centos hosts
redhat_java_package_name: java-1.8.0-openjdk

### Java Package to install on Debian hosts
debian_java_package_name: openjdk-8-jdk

### Java Package to install on Ubuntu hosts
ubuntu_java_package_name: openjdk-8-jdk

### Deb Repository to use for Java Installation
ubuntu_java_repository: ppa:openjdk-r/ppa

### Version of Jolokia Agent Jar to Download
jolokia_version: 1.6.2

### Full URL used for Jolokia Agent Jar Download
jolokia_jar_url: "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{{jolokia_version}}/jolokia-jvm-{{jolokia_version}}-agent.jar"

### Full URL used for Prometheus Exporter Jar Download
jmxexporter_jar_url: https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.12.0/jmx_prometheus_javaagent-0.12.0.jar

### Boolean to have cp-ansible download the Confluent CLI
confluent_cli_download_enabled: "{{rbac_enabled}}"

### Full path on hosts to install the Confluent CLI
confluent_cli_path: /usr/local/bin/confluent

### Base URL for Confluent's Archive Repositories
confluent_common_repository_archive_baseurl: "{{confluent_common_repository_baseurl}}/archive/{{confluent_repo_version}}"

### Name of the file to download from the Archive base URL
confluent_archive_file_name: "confluent-{{confluent_archive_version}}-{{confluent_archive_scala_version}}.tar.gz"

### Full URL of the Archive file to download when in Archive File deployment mode
confluent_common_repository_archive_url: "{{confluent_common_repository_archive_baseurl}}/{{confluent_archive_file_name}}"

### A path reference to a locally accessible archive file. If this file is found locally (i.e. remote_src=true) then it will be used. If it is not found then the target file will be downloaded from Confluent. This is the default path ansible-pull uses, which means if an archive file is included in an ansible-pull repository it will be used assuming it's name conforms to what is expected.
confluent_archive_file_path: "~/.ansible/pull/{{ inventory_hostname }}/{{confluent_archive_file_name}}"
