---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: Check 2 way tls line omitted in properties
      shell: |
        grep "confluent.metadata.server.ssl.truststore.location"  /etc/kafka/server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 1

- name: Verify - LDAPS
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: Check that LDAPS protocol is enabled
      shell: |
        grep -Fq "ldap.java.naming.provider.url=ldaps://ldap1:636"  /etc/kafka/server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: no
  tasks:
    - name: Check truststore property for trusting mds
      shell: |
        grep -Fq "ssl.truststore.location=/var/ssl/private/schema_registry.truststore.jks"  /etc/schema-registry/schema-registry.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: no
  tasks:
    - name: Check truststore property for trusting mds
      shell: |
        grep -Fq "ssl.truststore.location=/var/ssl/private/kafka_rest.truststore.jks"  /etc/kafka-rest/kafka-rest.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - name: Check truststore property for trusting mds
      shell: |
        grep -Fq "ssl.truststore.location=/var/ssl/private/kafka_connect.truststore.jks"  /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - ksql
  hosts: ksql
  gather_facts: no
  tasks:
    - name: Check truststore property for trusting mds
      shell: |
        grep -Fq "ssl.truststore.location=/var/ssl/private/ksql.truststore.jks"  /etc/ksql/ksql-server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center
  gather_facts: no
  tasks:
    - name: Check truststore property for trusting mds
      shell: |
        grep -Fq "confluent.controlcenter.streams.ssl.truststore.location=/var/ssl/private/control_center.truststore.jks"  /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
