---
# More Kafka Connect Replicator variables are defined in the confluent.variables role

### Boolean to reconfigure Kafka Connect Replicator's logging with the RollingFileAppender and log cleanup functionality.
kafka_connect_replicator_custom_log4j: "{{ custom_log4j }}"

kafka_connect_replicator_java_args:
  - "{% if kafka_connect_replicator_listener ['ssl_mutual_auth_enabled'] | default(ssl_mutual_auth_enabled) | bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if kafka_connect_replicator_jolokia_enabled|bool %}-javaagent:{{kafka_connect_replicator_jolokia_jar_path}}=config={{kafka_connect_replicator_jolokia_config}}{% endif %}"
  - "{% if kafka_connect_replicator_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{kafka_connect_replicator_jmxexporter_port}}:{{kafka_connect_replicator_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the Kafka Connect Replicator Process
kafka_connect_replicator_custom_java_args: ""

kafka_connect_replicator_final_java_args: "{{ kafka_connect_replicator_java_args + [ kafka_connect_replicator_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
kafka_connect_replicator_service_overrides:
  LimitNOFILE: 100000
  User: "{{ kafka_connect_replicator_user if kafka_connect_replicator_user != kafka_connect_replicator_default_user else '' }}"
  Group: "{{ kafka_connect_replicator_group if kafka_connect_replicator_group != kafka_connect_replicator_default_group else '' }}"
  ExecStart: "{% if installation_method == 'archive' %}{{ kafka_connect_replicator.server_start_file }} {{ kafka_connect_replicator.config_file }}{% endif %}"

# Key/Value Pairs with empty values will not be written into override.conf
kafka_connect_replicator_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xms256M -Xmx2G"
  KAFKA_OPTS: "{{ kafka_connect_replicator_final_java_args | java_arg_build_out }}"
  # Remove trailing slash if there is one
  LOG_DIR: "{{ kafka_connect_replicator_log_dir|regex_replace('\\/$', '') if kafka_connect_replicator_log_dir|regex_replace('\\/$', '') != kafka_connect_replicator_default_log_dir else '' }}"

### Time in seconds to wait before starting Kafka Connect Replicator Health Checks.
kafka_connect_replicator_health_check_delay: 30
