zookeeper_service_name: confluent-zookeeper
zookeeper_packages:
  - confluent-kafka-2.12
zookeeper:
  user: cp-kafka
  group: confluent
  config_file: /etc/kafka/zookeeper.properties
  systemd_file: /usr/lib/systemd/system/{{zookeeper_service_name}}.service
  systemd_override: /etc/systemd/system/{{zookeeper_service_name}}.service.d/override.conf

kafka_broker_service_name: confluent-kafka
kafka_broker_packages:
  - confluent-kafka-2.12
  - confluent-rebalancer
kafka_broker:
  user: cp-kafka
  group: confluent
  config_file: /etc/kafka/server.properties
  systemd_file: /usr/lib/systemd/system/{{kafka_broker_service_name}}.service
  systemd_override: /etc/systemd/system/{{kafka_broker_service_name}}.service.d/override.conf

schema_registry_service_name: confluent-schema-registry
schema_registry_packages:
  - confluent-schema-registry
schema_registry:
  user: cp-schema-registry
  group: confluent
  config_file: /etc/schema-registry/schema-registry.properties
  systemd_file: /usr/lib/systemd/system/confluent-schema-registry.service
  systemd_override: /etc/systemd/system/confluent-schema-registry.service.d/override.conf
