---
- name: Installing/Unarchiving Confluent Hub
  unarchive:
    src: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}"
    remote_src: "{{kafka_connect_confluent_hub_client.is_remote}}"
    #group: "{{kafka_connect_group}}"
    #owner: "{{kafka_connect_user}}"

- name: Symlinking Confluent Hub CLI
  file:
    src: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"
    dest: "/usr/share/bin/confluent-hub"
    state: link
    #group: "{{kafka_connect_group}}"
    #owner: "{{kafka_connect_user}}"
    
- name: "Installing Kafka Connect Connector(s) from Confluent Hub"
  shell: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub install --no-prompt --component-dir {{item.dest}} {{item.connector}}"
  with_items: kafka_connect_confluent_hub_plugins