---
- name: Creating Confluent Hub Install Dir
  file:
    path: "{{kafka_connect_confluent_hub_client.install_dir}}"
    state: directory
    group: "{{kafka_connect_group}}"
    owner: "{{kafka_connect_user}}"
    mode: 0755

- name: Download Confluent Hub Tar
  get_url:
    url: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
    timeout: "{{kafka_connect_confluent_hub_client.timeout}}"
  when: kafka_connect_confluent_hub_client.is_remote

- name: Copy Confluent Hub Tar
  copy:
    src: "{{kafka_connect_confluent_hub_client.file}}"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
  when: not kafka_connect_confluent_hub_client.is_remote

- name: Unarchiving Confluent Hub
  unarchive:
    src: "{{kafka_connect_confluent_hub_client.install_dir}}/confluent-hub-client-latest.tar.gz"
    dest: "{{kafka_connect_confluent_hub_client.install_dir}}"
    remote_src: true
    mode: 0755
    creates: "{{kafka_connect_confluent_hub_client.install_dir}}/bin/confluent-hub"
