- name: Grant role Security Admin to Connect user
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/SecurityAdmin -H "accept: application/json" -H "Authorization: Bearer{{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}","connect-cluster":"connect-cluster"}}'

- name: Grant Connect user ResourceOwner on the group that Connect nodes use to coordinate across the cluster
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Group","name":"connect-cluster","patternType":"LITERAL"}]}'

- name: Grant Connect ResourceOwner on the Config topic where Connect configs are stored
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"connect-cluster-configs","patternType":"LITERAL"}]}'

- name: Grant Connect ResourceOwner on the offset storage topic
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"connect-cluster-offsets","patternType":"LITERAL"}]}'

- name: Grant Connect ResourceOwner on the offset status topic
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"connect-cluster-status","patternType":"LITERAL"}]}'

# TODO decide on connect secret registry
# Below code will help w the rolebindings
# - name: Grant Connect user ResourceOwner on the secrets store group
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Group","name":"secret-registry","patternType":"LITERAL"}]}'
#
# - name: Grant Connect ResourceOwner on the _confluent-secrets topic
#   delegate_to: "{{ groups['kafka_broker'][0] }}"
#   delegate_facts: true
#   shell: |
#     curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster":"{{cluster_id.stdout}}"}},"resourcePatterns":[{"resourceType":"Topic","name":"_confluent-secrets","patternType":"LITERAL"}]}'
