---
- name: Remove the Zookeeper, Kafka Broker, Schema Registry and Kafka Rest Groups from Inventory
  hosts: zookeeper:kafka_broker:schema_registry:kafka_rest
  gather_facts: false
  tasks:
    # - name: Get Kafka Cluster ID from Embedded Rest Proxy
    #   uri:
    #     url: "https://{{ groups['kafka_broker'][0] }}:8090/kafka/v3/clusters"
    #     method: GET
    #     validate_certs: false
    #     body_format: json
    #     return_content: true
    #     status_code: 200
    #     url_username: "{{mds_super_user}}"
    #     url_password: "{{mds_super_user_password}}"
    #     force_basic_auth: true
    #   register: cluster_id_query
    #   when: cluster_id_source | default('erp') == 'erp'

    # - name: Parse Kafka Cluster ID from json query
    #   set_fact:
    #     kafka_cluster_id: "{{ cluster_id_query.json.data[0].cluster_id }}"
    #   when: cluster_id_source | default('erp') == 'erp'

    # - set_fact:
    #     confluent_replicator_consumer_rbac_cluster_id: "{{ kafka_cluster_id }}"
    #   when: cluster_id_source | default('erp') == 'zookeeper'

    - name: "Change {{item}} Group Name in Inventory File for MDS"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "{{item}}:"
        line: "{{item}}_mds:"
      delegate_to: 127.0.0.1
      run_once: true
      loop:
        - zookeeper
        - kafka_broker
        - schema_registry
        - kafka_rest

    - name: "Change {{item}} Group Name in Inventory File for cluster2"
      lineinfile:
        path: "{{inventory_dir}}/ansible_inventory.yml"
        regexp: "{{item}}2:"
        line: "{{item}}:"
      delegate_to: 127.0.0.1
      run_once: true
      loop:
        - zookeeper
        - kafka_broker
        - kafka_rest
        - confluent_replicator

    - name: Refresh Inventory
      meta: refresh_inventory

- name: Converge
  import_playbook: ../../../../all.yml
