---

# create consumer 

- name: Read Replicated Data from Cluster 2
  hosts: kafka_broker
  gather_facts: false
  tasks:

    # - name: Create Consumer
    #   uri:
    #     url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer
    #     method: POST
    #     headers:
    #       Content-Type: application/vnd.kafka.v2+json
    #       Accept: application/vnd.kafka.v2+json
    #     body_format: json
    #     body: '{"name": "my_consumer_instance", "format": "json", "auto.offset.reset": "earliest"}'
    #     status_code: 200
    #   run_once: true
    #   register: consumer_output

    - name: Subscribe to Consumer
      uri:
        url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer/instances/my_consumer_instance/subscription
        method: POST
        headers:
          Content-Type: application/vnd.kafka.v2+json
        body_format: json
        body: '{"topics":["test-replicator-source"]}'
        status_code: 204
      run_once: true

    - name: Retrieve replicated data via Consumer
      uri:
        url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer/instances/my_consumer_instance/records
        method: GET
        headers:
          Accept: application/vnd.kafka.json.v2+json
        status_code: 200
      run_once: true
      register: data_output

    # - name: Retrieve replicated data via Consumer
    #   uri:
    #     url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer/instances/my_consumer_instance/records
    #     method: GET
    #     return_content: yes
    #     headers:
    #       Accept: application/vnd.kafka.json.v2+json
    #     status_code: 200
    #   register: data_output


    - debug:
        msg: "{{data_output}}"

# - name: Create Consumer
#       uri:
#         url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer
#         method: POST
#         headers:
#           Content-Type: application/vnd.kafka.v2+json
#           Accept: application/vnd.kafka.v2+json
#         body_format: json
#         body: '{"name": "my_consumer_instance", "format": "avro", "auto.offset.reset": "earliest"}'
#         status_code: 200
#       run_once: true
#       register: consumer_output

#     - debug:
#         msg: "{{consumer_output}}"


#     - name: Subscribe to Consumer
#       uri:
#         url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer/instances/my_consumer_instance/subscription
#         method: POST
#         headers:
#           Content-Type: application/vnd.kafka.v2+json
#           Accept: application/vnd.kafka.v2+json
#         body_format: json
#         body: '{"topics":["test-replicator-source"]}'
#         status_code: 204
#       run_once: true
    
#     - name: Retrieve replicated data via Consumer
#       uri:
#         url: http://kafka-rest1:8082/consumers/test-replicator-source-consumer/instances/my_consumer_instance/records
#         method: GET
#         headers:
#           Content-Type: application/vnd.kafka.avro.v2+json
#           Accept: application/vnd.kafka.avro.v2+json
#         status_code: 200
#       run_once: true
#       register: data_output

#     - debug:
#         msg: "{{data_output}}"

