- hosts: zookeeper:broker:schema-registry:ksql:control-center:kafka-rest
  tasks:
  - import_role:
      name: confluent.preflight
  - import_role:
      name: confluent.common
  - import_role:
      name: confluent.kerberos
    when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts"

- hosts: zookeeper[0]
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.ssl_customcerts
    when: security_mode == "kerberos_ssl_customcerts" or security_mode == "ssl_customcerts"
  - import_role:
      name: confluent.ssl_CA
    when: security_mode == "ssl" or security_mode == "sasl_ssl" or security_mode == "kerberos_ssl"

# - hosts: zookeeper:broker:schema-registry:ksql:control-center:kafka-rest
#   tasks:
#   - import_role:
#       name: confluent.kerberos
#     when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts"

- hosts: zookeeper
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.zookeeper

- hosts: broker
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.kafka-broker

- hosts: schema-registry
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.schema-registry

- hosts: connect-distributed
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.connect-distributed

- hosts: ksql
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.ksql

- hosts: control-center
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.control-center

- hosts: kafka-rest
  gather_facts: no
  tasks:
  - import_role:
      name: confluent.kafka-rest
