- hosts: zookeeper:broker:schema-registry:connect-distributed:control-center:kafka-rest
  roles:
  # tasks:
  # - include_role:
    - confluent.preflight
    - confluent.common
# Use the first zookeeper hosts to generate certificates
- hosts: zookeeper[0]
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.ssl_CA
- hosts: kerberos
  tasks:
  - include_role:
      name: confluent.kerberos
- hosts: zookeeper
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.zookeeper
- hosts: broker
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.kafka-broker
- hosts: schema-registry
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.schema-registry
- hosts: connect-distributed
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.connect-distributed
- hosts: ksql
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.ksql
- hosts: control-center
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.control-center
- hosts: kafka-rest
  gather_facts: no
  roles:
  # tasks:
  # - include_role:
    - confluent.kafka-rest
