- hosts: preflight
  tasks:
  - import_role:
      name: confluent.preflight
- hosts: ssl_CA
  tasks:
  - import_role:
      name: confluent.ssl_customcerts
    when: security_mode == "kerberos_ssl_customcerts" or security_mode == "ssl_customcerts"
  - import_role:
      name: confluent.ssl_CA
    when: security_mode == "ssl" or security_mode == "sasl_ssl" or security_mode == "kerberos_ssl"
- hosts: kerberos
  tasks:
  - import_role:
      name: confluent.kerberos
    when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts"
- hosts: zookeeper
  tasks:
  - import_role:
      name: confluent.zookeeper
- hosts: broker
  tasks:
  - import_role:
      name: confluent.kafka-broker
- hosts: schema-registry
  tasks:
  - import_role:
      name: confluent.schema-registry
- hosts: connect-distributed
  tasks:
  - import_role:
      name: confluent.connect-distributed
- hosts: ksql
  tasks:
  - import_role:
      name: confluent.ksql
- hosts: control-center
  tasks:
  - import_role:
      name: confluent.control-center
- hosts: kafka-rest
  tasks:
  - import_role:
      name: confluent.kafka-rest
