- name: Host Prerequisites
  hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  tasks:
  - import_role:
      name: confluent.common
  - import_role:
      name: confluent.kerberos
    when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms and kerberos_configure|bool"
  - import_role:
      name: confluent.ssl
    when: kafka_broker_listeners | ssl_required

- name: Kafta Connect Provisioning
  hosts: kafka_connect
  gather_facts: no
  tags:
    - kafka_connect
  tasks:
  - import_role:
      name: confluent.kafka_connect
