---
all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /Users/lfanconfluent.io/lfan-test-fips.pem

    zookeeper:
      properties:
        initLimit: 6
        syncLimit: 3
      kafka_broker:
        properties:
          num.io.threads: 15

    ssl_enabled: false
    password_protection_enabled: true

    confluent_cli_download_enabled: true

zookeeper:
  hosts:
    ip-10-1-43-198.us-east-2.compute.internal:
       ansible_ssh_host: ec2-18-220-184-134.us-east-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-10-1-43-198.us-east-2.compute.internal:
      ansible_ssh_host: ec2-18-220-184-134.us-east-2.compute.amazonaws.com