all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    security_mode: ssl_customcerts
    
preflight:
  hosts:
    ip-10-0-0-194.eu-west-2.compute.internal:
    ip-10-0-0-84.eu-west-2.compute.internal:
    ip-10-0-0-110.eu-west-2.compute.internal:
    ip-10-0-0-144.eu-west-2.compute.internal:
    ip-10-0-0-183.eu-west-2.compute.internal:
    ip-10-0-0-94.eu-west-2.compute.internal:
    ip-10-0-0-75.eu-west-2.compute.internal:
    ip-10-0-0-41.eu-west-2.compute.internal:
    ip-10-0-0-109.eu-west-2.compute.internal:
    ip-10-0-0-152.eu-west-2.compute.internal:
    ip-10-0-0-160.eu-west-2.compute.internal:
    ip-10-0-0-125.eu-west-2.compute.internal:
    ip-10-0-0-34.eu-west-2.compute.internal:
ssl_CA:
  hosts:
    ip-10-0-0-34.eu-west-2.compute.internal:
zookeeper:
  hosts:
    ip-10-0-0-144.eu-west-2.compute.internal:
      zoo:
        my:
          id: 1
    ip-10-0-0-183.eu-west-2.compute.internal:
      zoo:
        my:
          id: 2
    ip-10-0-0-94.eu-west-2.compute.internal:
      zoo:
        my:
          id: 3
broker:
  hosts:
    ip-10-0-0-194.eu-west-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-10-0-0-84.eu-west-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-10-0-0-110.eu-west-2.compute.internal:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    ip-10-0-0-75.eu-west-2.compute.internal:
control-center:
  hosts:
    ip-10-0-0-160.eu-west-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-10-0-0-109.eu-west-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-10-0-0-109.eu-west-2.compute.internal:
    ip-10-0-0-152.eu-west-2.compute.internal:
kafka-rest:
  hosts:
    ip-10-0-0-41.eu-west-2.compute.internal:
ksql:
 hosts:
    ip-10-0-0-125.eu-west-2.compute.internal:
tools:
  hosts:
    ip-10-0-0-34.eu-west-2.compute.internal:

