all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true
    security_mode: sasl_ssl
preflight:
  hosts:
    ip-172-31-27-26.us-east-2.compute.internal:
    ip-172-31-16-117.us-east-2.compute.internal:
    ip-172-31-24-73.us-east-2.compute.internal:
    ip-172-31-28-103.us-east-2.compute.internal:
ssl_CA:
  hosts:
    ip-172-31-27-26.us-east-2.compute.internal:
zookeeper:
  hosts:
    ip-172-31-27-26.us-east-2.compute.internal:
    ip-172-31-16-117.us-east-2.compute.internal:
    ip-172-31-24-73.us-east-2.compute.internal:
broker:
  hosts:
    ip-172-31-27-26.us-east-2.compute.internal:
      kafka:
        broker:
          id: 1
    ip-172-31-16-117.us-east-2.compute.internal:
      kafka:
        broker:
          id: 2
    ip-172-31-24-73.us-east-2.compute.internal:
      kafka:
        broker:
          id: 3
control-center:
  hosts:
    ip-172-31-28-103.us-east-2.compute.internal:
tools:
  hosts:
    ip-172-31-27-26.us-east-2.compute.internal:
