---
- name: Kafka Broker Status Finding
  hosts: kafka_broker
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.variables

    - name: Check if Kafka Service Running
      shell: "systemctl show -p SubState {{kafka_broker_service_name}}"
      changed_when: false
      check_mode: false
      register: substate

    - set_fact:
        install_pattern: "{{ 'parallel' if substate.stdout != 'SubState=running' or kafka_broker_reconfiguration_pattern == 'parallel' else 'serial' }}"

    - name: "Group Hosts by Installation Pattern: Parallel or Serial"
      group_by:
        key: kafka_broker_{{install_pattern}}

- name: Kafka Broker Parallel Provisioning
  hosts: kafka_broker_parallel
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.kafka_broker

- name: Kafka Broker Serial Ordering
  hosts: kafka_broker_serial
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  vars_files:
    - roles/confluent.kafka_broker/defaults/main.yml
  tasks:
    - import_role:
        name: confluent.variables

    - name: Get ActiveControllerCount
      uri:
        url: "{{ kafka_broker_jolokia_active_controller_url }}"
        validate_certs: false
        return_content: true
        status_code: 200
      register: active_controller_count_query
      check_mode: false

    - set_fact:
        mode: "{{ 'non_controller' if active_controller_count_query['json']['value']['Value']|int == 0 else 'controller' }}"

    - name: "Group Hosts by kafka_broker Mode: Controller or Non Controller"
      group_by:
        key: kafka_broker_{{mode}}

- name: Kafka Broker Non Controllers Provisioning
  hosts: kafka_broker_non_controller
  serial: 1
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.kafka_broker

- name: Kafka Broker Controller Provisioning
  hosts: kafka_broker_controller
  gather_facts: false
  tags: kafka_broker
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.kafka_broker
