---
- name: Schema Registry Upgrade
  hosts: schema_registry
  gather_facts: false
  environment: "{{ proxy_env }}"
  tasks:
    - name: Schema Registry Role Bindings
      import_role:
        name: confluent.schema_registry
        tasks_from: rbac.yml
      vars:
        query_source: zookeeper
        copy_certs: false
