---
- name: Schema Registry Provisioning
  hosts: schema_registry
  # Start SR hosts serially because there is a race condition on topic creation when multiple hosts start at the same time
  serial: 1
  gather_facts: false
  tags: schema_registry
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: confluent.schema_registry
