- name: Zookeeper Upgrade - Prep
  hosts: zookeeper
  gather_facts: no
  # Running serial=1 because add_host has problems
  # https://stackoverflow.com/questions/42106527/ansible-how-to-call-module-add-host-for-all-hosts-of-the-play
  serial: 1
  tags:
    - prep
  tasks:
    - import_role:
        name: confluent.variables

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        zookeeper_current_version: "{{ ansible_facts.packages['confluent-kafka-2.12'][0]['version'] }}"

    - debug:
        msg: "Current version: {{zookeeper_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Get Leader/Follower
      shell: echo stat | nc localhost 2181 | grep Mode
      register: leader_query

    - name: Add host to Follower Group
      add_host:
        name: "{{ inventory_hostname }}"
        group: upgrade_zookeeper_followers
      delegate_to: localhost
      when:
        - '"follower" in leader_query.stdout'
        - zookeeper_current_version != confluent_package_version

    - name: Add host to Leader Group
      add_host:
        name: "{{ inventory_hostname }}"
        group: upgrade_zookeeper_leader
      delegate_to: localhost
      when:
        - '"leader" in leader_query.stdout'
        - zookeeper_current_version != confluent_package_version

    - debug:
        msg: "Leader: {{inventory_hostname}}"
      when: '"leader" in leader_query.stdout'

- name: Zookeeper Upgrade
  # Putting leader group last here with serial=1 so the leader runs last
  hosts: upgrade_zookeeper_followers,upgrade_zookeeper_leader
  serial: 1
  tags:
    - upgrade
  tasks:
    - import_role:
        name: confluent.variables

    - name: Upgrade Zookeeper
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ zookeeper_service_name }}"
        packages: "{{ zookeeper_packages }}"
        backup_files:
          - "{{ zookeeper.config_file }}"
          - "{{ zookeeper.systemd_file }}"
          - "{{ zookeeper.systemd_override }}"
        restore_files:
          - "{{ zookeeper.config_file }}"

    - name: Wait for Health Check to return
      shell: echo ruok | nc localhost 2181
      register: ruok
      until: ruok.rc == 0
      retries: 30
      delay: 5

    - name: Wait for Health Check to return OK
      shell: echo ruok | nc localhost 2181
      register: ruok
      until: '"imok" in ruok.stdout'
      retries: 30
      delay: 5
