- name: Kafka Connect Upgrade
  hosts: kafka_connect
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - name: Make sure Status Storage Topic Property set
      lineinfile:
        name: "{{kafka_connect.config_file}}"
        line: "status.storage.topic={{kafka_connect_status_storage_topic}}"
        regexp: status.storage.topic.*
        state: present

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        # arbitrary connect package selection here
        kafka_connect_current_version: "{{ ansible_facts.packages['confluent-kafka-connect-elasticsearch'][0]['version'] }}"

    - debug:
        msg: "Current version: {{kafka_connect_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Kafka Connect
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ kafka_connect_service_name }}"
        packages: "{{ kafka_connect_packages }}"
        backup_files:
          - "{{ kafka_connect.config_file }}"
          - "{{ kafka_connect.systemd_file }}"
          - "{{ kafka_connect.systemd_override }}"
        restore_files:
          - "{{ kafka_connect.config_file }}"
      when: kafka_connect_current_version != confluent_package_version

    - name: Wait for API to return 200
      uri:
        url: "http://localhost:8083/connectors"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      # when: ssl_enabled|bool
      # http vs https??
