- name: Schema Registry Upgrade
  hosts: schema_registry
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        schema_registry_current_version: "{{ ansible_facts.packages['confluent-schema-registry'][0]['version'] }}"

    - debug:
        msg: "Current version: {{schema_registry_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Schema Registry
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ schema_registry_service_name }}"
        packages: "{{ schema_registry_packages }}"
        backup_files:
          - "{{ schema_registry.config_file }}"
          - "{{ schema_registry.systemd_file }}"
          - "{{ schema_registry.systemd_override }}"
        restore_files:
          - "{{ schema_registry.config_file }}"
      when: schema_registry_current_version != confluent_package_version

    - name: Wait for API to return 200
      uri:
        url: "http://localhost:{{schema_registry_listener_port}}/config"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      # when: ssl_enabled|bool
      # http vs https??
