- name: KSQL Upgrade
  hosts: ksql
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        ksql_current_version: "{{ ansible_facts.packages['confluent-ksql'][0]['version'] }}"

    - debug:
        msg: "Current version: {{ksql_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Kafka Connect
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ ksql_service_name }}"
        packages: "{{ ksql_packages }}"
        backup_files:
          - "{{ ksql.config_file }}"
          - "{{ ksql.systemd_file }}"
          - "{{ ksql.systemd_override }}"
        restore_files:
          - "{{ ksql.config_file }}"
      when: ksql_current_version != confluent_package_version

    - name: Wait for API to return 200
      uri:
        url: "http://localhost:{{ksql_listener_port}}/info"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      # when: ssl_enabled|bool
      # http vs https??
