- name: Kafka Rest Upgrade
  hosts: kafka_rest
  serial: 1
  tasks:
    - import_role:
        name: confluent.variables

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        kafka_rest_current_version: "{{ ansible_facts.packages['confluent-kafka-rest'][0]['version'] }}"

    - debug:
        msg: "Current version: {{kafka_rest_current_version}}   Upgrade to version: {{confluent_package_version}}"

    - name: Upgrade Kafka Connect
      include_tasks: tasks/upgrade_component.yml
      vars:
        service_name: "{{ kafka_rest_service_name }}"
        packages: "{{ kafka_rest_packages }}"
        backup_files:
          - "{{ kafka_rest.config_file }}"
          - "{{ kafka_rest.systemd_file }}"
          - "{{ kafka_rest.systemd_override }}"
        restore_files:
          - "{{ kafka_rest.config_file }}"
      when: kafka_rest_current_version != confluent_package_version

    - name: Wait for API to return 200
      uri:
        url: "http://localhost:{{kafka_rest_port}}/topics"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
