- name: Kafka Broker Upgrade - Set Log Message Format Version to Current Version
  hosts: kafka_broker
  gather_facts: no
  serial: 1
  vars:
    kafka_broker_upgrade_end_version: 5.3
  tasks:
    - import_role:
        name: confluent.variables_handlers

    - set_fact:
        log_message_format_version: 2.3
      when: kafka_broker_upgrade_end_version is match('5.3.*')

    - set_fact:
        log_message_format_version: 2.4
      when: kafka_broker_upgrade_end_version is match('5.4.*')

    - name: Set Log Message Format Version to Current Version
      lineinfile:
        name: "{{kafka_broker.config_file}}"
        line: "log.message.format.version={{log_message_format_version}}"
        regexp: log.message.format.version.*
        state: present
      notify:
        - Restart Kafka
        - Wait for URP
