- name: Schema Registry Upgrade
  hosts: schema_registry
  # Running serial=1 because add_host has problems
  # https://stackoverflow.com/questions/42106527/ansible-how-to-call-module-add-host-for-all-hosts-of-the-play
  serial: 1
  tags:
    - prep
  tasks:
    - import_role:
        name: confluent.variables

    - package_facts:
        manager: auto

    - name: Get Current Package Version
      set_fact:
        schema_registry_current_version: "{{ ansible_facts.packages['confluent-schema-registry'][0]['version'] }}"

    - debug: var=schema_registry_current_version

    - name: Create Backup Directory
      file:
        path: /tmp/upgrade/schema-registry
        state: directory
        mode: 0640

    - name: Backup Configuration files
      copy:
        src: "{{ item }}"
        remote_src: yes
        dest: "/tmp/upgrade/schema-registry/{{ item | basename }}"
      loop:
        - "{{ schema_registry.config_file }}"
        - "{{ schema_registry.systemd_file }}"
        - "{{ schema_registry.systemd_override }}"

    - name: Stop Schema Registry Service
      systemd:
        name: "{{ schema_registry_service_name }}"
        state: stopped

    - name: Configure Repositories
      import_role:
        name: confluent.common
      vars:
        install_java: false

    - name: Install the Schema Registry Packages - Red Hat
      yum:
        name: "{{item}}-{{confluent.package_version}}"
        state: latest
      loop: "{{ schema_registry_packages }}"
      when: ansible_os_family == "RedHat"

    - name: Install the Schema Registry Packages - Debian
      apt:
        name: "{{item}}={{confluent.package_version}}"
        update_cache: yes
      loop: "{{ schema_registry_packages }}"
      when: ansible_os_family == "Debian"

    - name: Put back configuration
      copy:
        dest: "{{ item }}"
        remote_src: yes
        src: "/tmp/upgrade/schema-registry/{{ item | basename }}"
      loop:
        - "{{ schema_registry.config_file }}"

    - name: Restart Schema Registry Service
      systemd:
        name: "{{ schema_registry_service_name }}"
        state: restarted
