---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: Check kerberos line on broker listener
      shell: |
        grep -Fq "listener.name.broker.gssapi.sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required" /etc/kafka/server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: no
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://kafka-broker" /etc/schema-registry/schema-registry.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://kafka-broker" /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: no
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://kafka-broker" /etc/kafka-rest/kafka-rest.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - ksql
  hosts: ksql
  gather_facts: no
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://kafka-broker" /etc/ksql/ksql-server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center
  gather_facts: no
  tasks:
    - name: Check mds is http
      shell: |
        grep -Fq "confluent.metadata.bootstrap.server.urls=http://kafka-broker" /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
