---
# Run these tasks over kafka_broker group with serial: 1
# Creates two variable defined groups: non_controller_group, controller
# confluent_server_enabled and kafka_broker_jolokia_ssl_enabled vars must be set correctly for the host
- import_role:
    name: confluent.variables

- name: Search for Zookeeper SSL Property
  shell: "grep 'zookeeper.ssl.client.enable' {{kafka_broker.config_file}}"
  register: zk_ssl_grep
  failed_when: false
  changed_when: false
  check_mode: false

- name: Get Controller Broker ID
  shell: |
    {{ binary_base_path }}/bin/zookeeper-shell {{ groups['zookeeper'][0] }}:{{zookeeper_client_port}} \
      {% if zk_ssl_grep.rc == 0 %}--zk-tls-config-file {{kafka_broker.config_file}}{% endif %} \
      get /controller | grep brokerid
  register: controller_query
  run_once: true
  changed_when: false
  check_mode: false

- name: Search for Kafka Broker ID
  shell: "grep '^broker.id' {{kafka_broker.config_file}}"
  register: broker_id_grep
  changed_when: false
  check_mode: false

- set_fact:
    controller_json: "{{controller_query.stdout}}"
    broker_id: "{{broker_id_grep.stdout | regex_replace('^[-a-zA-Z0-9.]*[ ]?=[ ]?(.*)$', '\\1')}}"

- debug:
    msg: "Broker ID: {{broker_id}} and Controller ID: {{controller_json.brokerid}}"

- name: Add host to Non Controller Group
  add_host:
    name: "{{ inventory_hostname }}"
    group: "{{ non_controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int != controller_json.brokerid|int

- name: Add host to Controller Group
  add_host:
    name: "{{ inventory_hostname }}"
    group: "{{ controller_group }}"
  delegate_to: localhost
  changed_when: false
  when: broker_id|int == controller_json.brokerid|int
