---
# TODO this needs to move into the component role since it has wrong user on it
- name: Copy in public pem files
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"

- name: Get Kafka Cluster ID from Zookeeper
  shell: /bin/zookeeper-shell localhost:2181 get /cluster/id | grep version
  delegate_to: "{{ groups['zookeeper'][0] }}"
  register: cluster_id_query

- set_fact:
    cluster_id_json: "{{ cluster_id_query.stdout }}"

- name: Set cluster_id Variable
  set_fact:
    cluster_id: "{{ cluster_id_json.id }}"

- set_fact:
    certificate_args: ""
  when: not mds_ssl_enabled|bool

- set_fact:
    certificate_args: "--cacert /var/ssl/private/ca.crt"
  when: mds_ssl_enabled|bool and not mds_ssl_mutual_auth_enabled|bool

- set_fact:
    certificate_args: "--cacert /var/ssl/private/ca.crt --key /var/ssl/private/kafka_broker.key --cert /var/ssl/private/kafka_broker.crt"
  when: mds_ssl_enabled|bool and mds_ssl_mutual_auth_enabled|bool

- name: Login to MDS to get Security Token
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl {{certificate_args}} -u "{{mds_super_user}}":"{{mds_super_user_password}}" \
      -s {{mds_http_protocol}}://"{{ groups['kafka_broker'][0] }}":8090/security/1.0/authenticate
  register: rbac_token_query

- set_fact:
    rbac_token_query_stdout: "{{ rbac_token_query.stdout }}"

- name: Set rbac_token Variable
  set_fact:
    rbac_token: "{{ rbac_token_query_stdout.auth_token }}"
