- set_fact:
      principal_name: "{{inventory_hostname}}"
  when: not ssl_custom_certs|bool or not ssl_provided_keystore_and_truststore|bool

- set_fact:
      principal_name: "{{rbac_principal_name}}"
  when: ssl_custom_certs|bool or ssl_provided_keystore_and_truststore|bool

- name: Copy in public pem files
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"

- name: Get Kafka Cluster ID from Zookeeper
  delegate_to: "{{ groups['zookeeper'][0] }}"
  shell: |
    /bin/zookeeper-shell localhost:2181 get /cluster/id 2> /dev/null | grep version | jq -r .id
  register: cluster_id  

- name: export CA to pem format for MDS login to create user
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  shell: |
    openssl pkcs12 -in /var/ssl/private/kafka_broker.truststore.jks \
      -out /var/ssl/private/kafka_broker.truststore.pem \
      -passin pass:{{kafka_broker_truststore_storepass}} -passout pass:{{kafka_broker_truststore_storepass}}

- name: convert keystore to pem format
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  shell: |
    keytool -noprompt -importkeystore -srckeystore /var/ssl/private/kafka_broker.keystore.jks -srcstorepass {{kafka_broker_keystore_storepass}} -destkeystore /var/ssl/private/kafka_broker.keystore.p12 -deststoretype PKCS12 -deststorepass {{kafka_broker_keystore_storepass}} -destkeypass {{kafka_broker_keystore_storepass}}

- name: export certificate from pem
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  shell: |
    openssl pkcs12 -in /var/ssl/private/kafka_broker.keystore.p12 -nokeys -out /var/ssl/private/cert.pem -passin pass:{{kafka_broker_keystore_storepass}}

- name: export private key from pem
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  shell: |
    openssl pkcs12 -in /var/ssl/private/kafka_broker.keystore.p12 -nodes -nocerts -out /var/ssl/private/key.pem -passin pass:{{kafka_broker_keystore_storepass}}

- name: Login to MDS to get Security Token
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -u "{{mds_super_user}}":"{{mds_super_user_password}}" -s https://"{{ groups['kafka_broker'][0] }}":8090/security/1.0/authenticate 2> /dev/null | grep auth_token | jq -r .auth-token
  register: rbac_token

