---
- name: Get Kafka Cluster ID from Embedded Rest Proxy
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/kafka/v3/clusters"
    method: GET
    validate_certs: false
    body_format: json
    return_content: true
    status_code: 200
  register: cluster_id_query

- name: Parse Kafka Cluster ID from json query
  set_fact:
    kafka_cluster_id: "{{ cluster_id_query.json | json_query('data[0].cluster_id') }}"

- name: Create SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755

- name: Copy in MDS Public Pem File
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{user}}"
    group: "{{group}}"
