---
- name: Create Secrets Protection Directory
  file:
    path: /var/ssl/private/
    state: directory
    mode: 0755

- name: Copy security.properties file to Host
  copy:
    src: "{{ secrets_protection_security_file }}"
    dest: "/var/ssl/private/security.properties"

- name: Encrypt All Properties that Contain 'password'
  shell: |
    /usr/local/bin/confluent secret file encrypt --config-file {{ config_path }} \
      --local-secrets-file /var/ssl/private/security.properties \
      --remote-secrets-file /var/ssl/private/security.properties
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: not params

- name: Encrypt Selected Properties
  shell: |
    /usr/local/bin/confluent secret file encrypt --config-file {{ config_path }} \
      --local-secrets-file /var/ssl/private/security.properties \
      --remote-secrets-file /var/ssl/private/security.properties \
      --config {{ item }}
  loop: "{{ params }}"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: params|length>0
