---
- name: Add Confluent CLI to path
  shell: "export PATH=/usr/local/bin/bin:${PATH};"

- copy:
    content: "{{ secrets_protection_security_file }}"
    dest: "security.properties"

# If no paramaters are specified, any property that contains
# the string password is encrypted in the configuration key
- name: Encrypt Properties - Standard
  shell: "confluent secret file encrypt --config-file {{ config_path }} \
  --local-secrets-file ./security.properties \
  --remote-secrets-file ./security.properties"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: not params

- name: Encrypt Properties - Custom
  shell: "confluent secret file encrypt --config-file {{ config_path }} \
           --local-secrets-file ./security.properties \
           --remote-secrets-file ./security.properties \
           --config {{ item }}"
  loop: "{{ params }}"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: params|length>0