---
- name: Add security.properties file to Host
  shell: "mkdir -p var/ssl/private"

- copy:
    content: "{{ secrets_protection_security_file }}"
    dest: "/var/ssl/private/security.properties"

# If no paramaters are specified, any property that contains
# the string password is encrypted in the configuration key
- name: Encrypt Properties - Standard
  shell: "/usr/local/bin/confluent secret file encrypt --config-file {{ config_path }} \
  --local-secrets-file /var/ssl/private/security.properties \
  --remote-secrets-file /var/ssl/private/security.properties"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: not params

- name: Encrypt Properties - Custom
  shell: "/usr/local/bin/confluent secret file encrypt --config-file {{ config_path }} \
           --local-secrets-file /var/ssl/private/security.properties \
           --remote-secrets-file /var/ssl/private/security.properties \
           --config {{ item }}"
  loop: "{{ params }}"
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  when: params|length>0