---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.variables
  
    - name: Check confluent cli is installed
      command: "{{confluent_cli_path}} version"

    - name: Verify configuration is encrypted
      import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: config.providers.securepass.class
        expected_value: io.confluent.kafka.security.config.provider.SecurePassConfigProvider