---
- name: Export Kafka Error Logs
  shell: "journalctl -u {{kafka_broker_service_name}} --since -10m > /tmp/{{kafka_broker_service_name}}.log"

- name: Fetch Files for Investigation
  fetch:
    src: "{{item}}"
    dest: "error_files/{{inventory_hostname}}-{{item|basename}}"
    flat: true
    fail_on_missing: false
  loop:
    - "{{kafka_broker.config_file}}"
    - "/tmp/{{kafka_broker_service_name_service_name}}.log"

- name: Fail Kafka Broker Installation
  fail:
    msg: Kafka Broker health check failed. Review log and property files in error_files/ directory
