---
- block:
    - name: Wait for Under Replicated Partitions Metric to return 200
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        return_content: true
        status_code: 200
      register: result
      until: result.status == 200
      retries: 40
      delay: 5

    - name: Wait for Under Replicated Partitions Metric to return Data
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        return_content: true
        status_code: 200
      register: result
      until: result['json']['value'] is defined
      retries: 40
      delay: 5

    # curl localhost:7771/jolokia/read/kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions
    # {"request":{"mbean":"kafka.server:name=UnderReplicatedPartitions,type=ReplicaManager","type":"read"},"value":{"Value":0},"timestamp":1565819946,"status":200}
    - name: Wait for Under Replicated Partitions Metric to equal Zero
      uri:
        url: "{{ kafka_broker_jolokia_urp_url }}"
        validate_certs: false
        return_content: true
        status_code: 200
      register: result
      until: result['json']['value']['Value'] == 0
      retries: 40
      delay: 5
  when: not ansible_check_mode and jolokia_enabled|bool

- name: Wait for Embedded Rest Proxy to start - RBAC
  uri:
    url: "{{kafka_broker_erp_clusters_url}}"
    validate_certs: false
    return_content: true
    status_code: 200
  register: result
  until: result['json']['kind'] is defined
  retries: 40
  delay: 5
  when:
    - not ansible_check_mode
    - kafka_broker_rest_endpoint_enabled|bool
    - not rbac_enabled|bool

- name: Wait for Embedded Rest Proxy to start - RBAC
  uri:
    url: "{{kafka_broker_erp_clusters_url}}"
    validate_certs: false
    return_content: true
    status_code:
      - 200
      - 401
  register: result
  until: result.status == 200 or result.status == 401
  retries: 40
  delay: 5
  when: not ansible_check_mode and kafka_broker_rest_endpoint_enabled | bool
