---
- name: Populate Service Facts
  service_facts:

- block:
    - name: Restart confluent-server Serially
      include: restart.yml
      delegate_to: "{{ item }}"
      loop: "{{ groups['kafka_broker'] }}"
      when:
        - "hostvars[item].inventory_hostname == inventory_hostname"
        - ansible_facts.services['confluent-server.service'].state == 'running'

    - name: Restart confluent-server in Parallel
      include: restart.yml
      when: ansible_facts.services['confluent-server.service'].state != 'running'
  when: confluent_server_enabled|bool

- block:
    - name: Restart confluent-server Serially
      include: restart.yml
      delegate_to: "{{ item }}"
      loop: "{{ groups['kafka_broker'] }}"
      when:
        - "hostvars[item].inventory_hostname == inventory_hostname"
        - ansible_facts.services['confluent-kafka.service'].state == 'running'

    - name: Restart confluent-server in Parallel
      include: restart.yml
      when: ansible_facts.services['confluent-kafka.service'].state != 'running'
  when: not confluent_server_enabled|bool
