---
- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create CA
  shell: |
    openssl req -new -x509 -keyout {{ssl_self_signed_ca_key_filename}} \
      -out {{ssl_self_signed_ca_cert_filename}} -days {{CA_expiration_days}} \
      -subj '/CN=ca1.test.confluent.io/OU=TEST/O=CONFLUENT/L=PaloAlto/S=Ca/C=US' \
      -passin pass:{{ssl_self_signed_ca_password}} -passout pass:{{ssl_self_signed_ca_password}}
  args:
    chdir: /var/ssl/private/generation

- name: Copy CA Back to Ansible Hosts
  synchronize:
    src: /var/ssl/private/generation/
    dest: generated_ssl_files
    mode: pull
