---
- name: Create Custom Certs
  import_playbook: ../certificates.yml

- name: Provision LDAP Server
  import_playbook: ../ldap.yml

- name: Provision Kerberos Server
  import_playbook: ../kerberos.yml

- name: Host Prerequisites
  hosts: zookeeper:kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.common
      tags: common

- name: Zookeeper Provisioning
  hosts: zookeeper
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.zookeeper

- name: Kafka Broker Provisioning
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.kafka_broker
