# - name: restart kafka-rest
#   systemd:
#     daemon_reload: true
#     name: "{{kafka_rest_service_name}}"
#     state: restarted

- name: restart kafka-rest
  include_tasks: tasks/restart_kafka_rest.yml
