---
- name: Install and configure OpenLDAP
  hosts: ldap_server
  tasks:
    - import_role:
        name: confluent.ldap

- hosts: kerberos_server
  tasks:
    - import_role:
        name: kerberos_server
