---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: no
  tasks:

    - name: Check kerberos line on broker listener
      shell: |
        grep -Fq "listener.name.broker.gssapi.sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required" /etc/kafka/server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
