---
- name: Verify - zookeeper
  hosts: zookeeper
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/zookeeper.properties
        property: ssl.quorum.ciphersuites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/server.properties
        property: zookeeper.ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/schema-registry/schema-registry.properties
        property: ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka-rest/kafka-rest.properties
        property: ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: value.converter.schema.registry.ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - ksql
  hosts: ksql
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/ksqldb/ksql-server.properties
        property: ksql.schema.registry.ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

- name: Verify - control_center
  hosts: control_center
  gather_facts: false
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/confluent-control-center/control-center-production.properties
        property: confluent.controlcenter.rest.ssl.cipher.suites
        expected_value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
