zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
    sasl_port: 9092
kerberos:
  keytab_dir: /etc/security/keytabs
confluent:
  support:
    customer_id: anonymous
    metrics_enabled: true
