zookeeper:
  properties:
    clientPort: 2181
kafka_port: 9092
kerberos:
  keytab_dir: /etc/security/keytabs
confluent:
  package_version: 5.3.0-1
  repo_version: 5.3
  support:
    customer_id: anonymous
    metrics_enabled: true

jolokia_jar_path: /opt/jolokia/jolokia.jar
jolokia_java_arg: "-javaagent:{{jolokia_jar_path}}=port=8778,host=0.0.0.0"
