control_center_open_file_limit: "{{open_file_limit}}"
control_center_service_overrides:
  LimitNOFILE: "{{control_center_open_file_limit}}"
control_center_service_environment_overrides:
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"

control_center:
  properties:
    confluent.controlcenter.streams.num.stream.threads: 8
    confluent.controlcenter.data.dir: /var/lib/confluent/control-center
    confluent.controlcenter.ksql.enable: 'true'
    confluent.controlcenter.schema.registry.enable: 'true'
    confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
    confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
