control_center_ssl_java_arg_buildout: "-Djavax.net.ssl.keyStore={{keystore_path}} -Djavax.net.ssl.trustStore={{truststore_path}} -Djavax.net.ssl.keyStorePassword={{keystore_storepass}} -Djavax.net.ssl.trustStorePassword={{truststore_storepass}}"
control_center_ssl_java_arg: "{{ control_center_ssl_java_arg_buildout if schema_registry_ssl_enabled|bool else '' }}"

control_center_open_file_limit: "{{open_file_limit}}"
control_center_service_overrides:
  LimitNOFILE: "{{control_center_open_file_limit}}"
control_center_service_environment_overrides:
  CONTROL_CENTER_HEAP_OPTS: "-Xmx6g"
  CONTROL_CENTER_OPTS: "{{control_center_ssl_java_arg}}"

control_center:
  properties:
    confluent.controlcenter.streams.num.stream.threads: 8
    confluent.controlcenter.data.dir: /var/lib/confluent/control-center
    confluent.controlcenter.ksql.enable: 'true'
    confluent.controlcenter.schema.registry.enable: 'true'
