zookeeper_open_file_limit: "{{open_file_limit}}"

zookeeper_jaas_file: /etc/kafka/zookeeper_jaas.conf
zookeeper_jaas_java_arg_buildout: "-Djava.security.auth.login.config={{zookeeper_jaas_file}}"

zookeeper_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{zookeeper_jolokia_port}},host=0.0.0.0"

zookeeper_custom_java_args: ""
zookeeper_java_args:
  - "{{ zookeeper_jaas_java_arg_buildout if sasl_protocol == 'kerberos' else '' }}"
  - "{{ zookeeper_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"

zookeeper_final_java_args: "{{ zookeeper_java_args + [ zookeeper_custom_java_args ] }}"

zookeeper_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx1g"
  KAFKA_OPTS: "{{ zookeeper_final_java_args | java_arg_build_out }}"
zookeeper_service_overrides:
  LimitNOFILE: "{{zookeeper_open_file_limit}}"

zookeeper:
  properties:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
