---
# More zookeeper variables are defined in the confluent.variables role

### Boolean to reconfigure Zookeeper's logging with RollingFileAppender and log cleanup
zookeeper_log4j_rolling_enabled: "{{ log4j_rolling_enabled }}"

zookeeper_java_args:
  - "{% if zookeeper_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if zookeeper_sasl_protocol in ['kerberos', 'digest'] %}-Djava.security.auth.login.config={{zookeeper.jaas_file}}{% endif %}"
  - "{% if zookeeper_jolokia_enabled|bool %}-javaagent:{{jolokia_jar_path}}=port={{zookeeper_jolokia_port}},host=0.0.0.0{% if zookeeper_jolokia_ssl_enabled|bool %},keystore={{zookeeper_keystore_path}},keystorePassword={{zookeeper_keystore_storepass}},protocol=https{% endif %}{% endif %}"
  - "{% if zookeeper_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{zookeeper_jmxexporter_port}}:{{zookeeper_jmxexporter_config_path}}{% endif %}"
  - "-Dlog4j.configuration=file:{{zookeeper.log4j_file}}"

### Custom Java Args to add to the Zookeeper Process
zookeeper_custom_java_args: ""

zookeeper_final_java_args: "{{ zookeeper_java_args + [ zookeeper_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
zookeeper_service_overrides:
  User: "{{ zookeeper_user if zookeeper_user != zookeeper_default_user else '' }}"
  Group: "{{ zookeeper_group if zookeeper_group != zookeeper_default_group else '' }}"
  ExecStart: "{% if installation_method == 'archive' %}{{ zookeeper.server_start_file }} {{ zookeeper.config_file }}{% endif %}"

# Key/Value Pairs with empty values will not be written into override.conf
zookeeper_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xmx1g"
  KAFKA_OPTS: "{{ zookeeper_final_java_args | java_arg_build_out }}"
  LOG_DIR: "{{ zookeeper_log_dir if zookeeper_log_dir != zookeeper_default_log_dir else '' }}"
  CONFLUENT_SECURITY_MASTER_KEY: "{% if zookeeper_secrets_protection_enabled|bool %}{{secrets_protection_masterkey}}{% endif %}"
