- name: create ssl certificate directory
  file:
    path: /var/ssl/private
    state: directory
    mode: 0755
- name: copy CA Certs to host
  copy:
    src: "{{ssl_ca_certificate_path}}"
    dest: /var/ssl/private
    mode: 0644
- name: copy host Certs to host
  copy:
    src: "{{ssl_host_key_path}}"
    dest: /var/ssl/private
    mode: 0644
- name: Import SSL Certs
  script: scripts/certs-create.sh "{{ssl_ca_certificate_path}}" "{{ssl_host_key_path}}" "{{host_keystore_CN}}" "{{host_keystore_OU}}" "{{host_keystore_O}}" "{{host_keystore_L}}" "{{host_keystore_ST}}" "{{host_keystore_Country}}" "{{host_keystore_storepass}}" "{{host_keystore_keypass}}" 
  args:
    chdir: /var/ssl/private
    creates: /var/ssl/private/broker.keystore.jks
- name: copy ssl related files to local ansible host
  synchronize:
    src: /var/ssl/private/
    dest: generated_ssl_files
    mode: pull

