kafka_rest_jolokia_java_arg: "-javaagent:{{jolokia_jar_path}}=port={{kafka_rest_jolokia_port}},host=0.0.0.0"
kafka_rest_open_file_limit: "{{open_file_limit}}"
kafka_rest_service_overrides:
  LimitNOFILE: "{{kafka_rest_open_file_limit}}"
kafka_rest_service_environment_overrides:
  LOG_DIR: /var/log/kafka-rest
  KAFKAREST_OPTS: "{{kafka_rest_jolokia_java_arg}}"

kafka_rest:
  properties:
    listeners: "http://0.0.0.0:{{kafka_rest_port}}"
    client.ssl.endpoint.identification.algorithm: ""
