kafka_rest_jolokia_java_arg_buildout: "-javaagent:{{jolokia_jar_path}}=port={{kafka_rest_jolokia_port}},host=0.0.0.0"

kafka_rest_ssl_java_arg_buildout: "-Djavax.net.ssl.keyStore={{kafka_rest_keystore_path}} -Djavax.net.ssl.trustStore={{kafka_rest_truststore_path}} -Djavax.net.ssl.keyStorePassword={{kafka_rest_keystore_storepass}} -Djavax.net.ssl.trustStorePassword={{kafka_rest_truststore_storepass}}"

kafka_rest_custom_java_args: ""
kafka_rest_java_args:
  - "{{ kafka_rest_jolokia_java_arg_buildout if jolokia_enabled|bool else '' }}"
  - "{{ kafka_rest_ssl_java_arg_buildout if schema_registry_ssl_enabled|bool else '' }}"

kafka_rest_final_java_args: "{{ kafka_rest_java_args + [ kafka_rest_custom_java_args ] }}"

kafka_rest_open_file_limit: "{{open_file_limit}}"
kafka_rest_service_overrides:
  LimitNOFILE: "{{kafka_rest_open_file_limit}}"
kafka_rest_service_environment_overrides:
  LOG_DIR: /var/log/kafka-rest
  KAFKAREST_OPTS: "{{ kafka_rest_final_java_args | java_arg_build_out }}"

kafka_rest:
  properties:
    id: "{{groups.kafka_rest.index(inventory_hostname) + 1}}"
