---
- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_property.yml
      vars:
        file_path: /etc/kafka/connect-distributed.properties
        property: security.protocol
        expected_value: SSL
