zookeeper:
  properties:
    clientPort: 2181
kafka_port: 9092
control_center_listenter_port: 9021
schema_registry_listener_port: 8081
kafka_rest_port: 8082
kafka_connect_rest_port: 8083
ksql_listener_port: 8088

kerberos:
  keytab_dir: /etc/security/keytabs

confluent_repo_version: 5.3
confluent_package_version: 5.3.0
confluent_full_package_version: "{{ confluent_package_version + '-1' }}"
confluent_package_redhat_suffix: "{{ '-' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"
confluent_package_debian_suffix: "{{ '=' + confluent_full_package_version if confluent_full_package_version != '' else ''}}"

confluent:
  support:
    customer_id: anonymous
    metrics_enabled: true

jolokia_jar_path: /opt/jolokia/jolokia.jar
zookeeper_jolokia_port: 7770
kafka_broker_jolokia_port: 7771
schema_registry_jolokia_port: 7772
kafka_connect_jolokia_port: 7773
ksql_jolokia_port: 7774
kafka_rest_jolokia_port: 7775

open_file_limit: 500000

host_truststore_storepass: confluent
host_keystore_storepass: confluent
host_cert_password: confluent

ssl_enabled: "{{ true if 'ssl' in security_mode else false }}"

kafka_connect_status_storage_topic: connect-status

jolokia_enabled: true

rbac_enabled: false
confluent_server_enabled: "{{ true if rbac_enabled|bool else false }}"
