---
# Loops over all kafka hosts, but only runs when current host, delegated to current host
- name: Serial Restart
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['kafka_broker'] }}"
  when: "hostvars[item].inventory_hostname == inventory_hostname"
