---
# More kafka_connect variables are defined in the confluent.variables role

### Boolean to reconfigure Kafka Connect's logging with the RollingFileAppender and log cleanup functionality.
confluent_replicator_custom_log4j: "{{ custom_log4j }}"

confluent_replicator_java_args:
  - "{% if confluent_replicator_ssl_enabled|bool %}-Djdk.tls.ephemeralDHKeySize=2048{% endif %}"
  - "{% if confluent_replicator_jolokia_enabled|bool %}-javaagent:{{confluent_replicator_jolokia_jar_path}}=config={{confluent_replicator_jolokia_config}}{% endif %}"
  - "{% if confluent_replicator_jmxexporter_enabled|bool %}-javaagent:{{jmxexporter_jar_path}}={{confluent_replicator_jmxexporter_port}}:{{confluent_replicator_jmxexporter_config_path}}{% endif %}"

### Custom Java Args to add to the Connect Process
confluent_replicator_custom_java_args: ""

confluent_replicator_final_java_args: "{{ confluent_replicator_java_args + [ confluent_replicator_custom_java_args ] }}"

# Key/Value Pairs with empty values will not be written into override.conf
confluent_replicator_service_overrides:
  LimitNOFILE: 100000
  User: "{{ confluent_replicator_user if confluent_replicator_user != confluent_replicator_default_user else '' }}"
  Group: "{{ confluent_replicator_group if confluent_replicator_group != confluent_replicator_default_group else '' }}"
  ExecStart: "{% if installation_method == 'archive' %}{{ confluent_replicator.server_start_file }} {{ confluent_replicator.config_file }}{% endif %}"

# Key/Value Pairs with empty values will not be written into override.conf
confluent_replicator_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xms256M -Xmx2G"
  KAFKA_OPTS: "{{ confluent_replicator_final_java_args | java_arg_build_out }}"
  # Remove trailing slash if there is one
  LOG_DIR: "{{ confluent_replicator_log_dir|regex_replace('\\/$', '') if confluent_replicator_log_dir|regex_replace('\\/$', '') != confluent_replicator_default_log_dir else '' }}"
  # CONFLUENT_SECURITY_MASTER_KEY: "{% if confluent_replicator_secrets_protection_enabled|bool %}{{secrets_protection_masterkey}}{% endif %}"
