version: '2'
services:
  db2server:
    image: debezium/db2-cdc:1.5
    privileged: True
    ports:
     - 50000:50000
    environment:
     - LICENSE=accept
     - DBNAME=TESTDB
     - DB2INST1_PASSWORD==Password!
    volumes:
     - ./db2data:/database
