---
# Cannot use Block/Rescue in Ansible Handlers: https://github.com/ansible/ansible/issues/14270
# Implementing try/catch logic with ignore_errors and conditionals
- name: Wait for webpage to serve content
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
  register: result1
  until: result1.status == 200
  retries: 40
  delay: 10
  when: not rbac_enabled|bool
  ignore_errors: true

- name: Wait for webpage to serve content - RBAC
  uri:
    url: "{{control_center_http_protocol}}://{{inventory_hostname}}:{{control_center_port}}"
    validate_certs: false
    url_username: "{{control_center_ldap_user}}"
    url_password: "{{control_center_ldap_password}}"
    force_basic_auth: true
  register: result2
  until: result2.status == 200
  retries: 40
  delay: 10
  when: rbac_enabled|bool
  ignore_errors: true

- name: Fetch Files for Debugging Failure
  include: failure_handling.yml
  vars:
    service_name: "{{control_center_service_name}}"
    config_file: "{{control_center.config_file}}"
  # Only one health check runs, only one will have a 'failed' field. For skipped checks, defaulting 'failed' to False
  when: result1.failed|default(False) or result2.failed|default(False)
