---
- name: Install and Configure Kerberos
  include_role:
    name: confluent.kerberos
  when: kerberos_configure|bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{control_center.group}}"
    mode: '650'
    recurse: yes

- name: Copy in Keytab File
  copy:
    src: "{{control_center_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{control_center_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - restart control center
