# Install Packages
- name: Install the Control Center Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Control Center Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
    update_cache: yes
  loop: "{{control_center_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Control Center Group
  group:
    name: "{{control_center.group}}"

- name: Create Control Center User
  user:
    name: "{{control_center.user}}"
    comment: "Control Center User"
    system: yes
    group: "{{control_center.group}}"

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{control_center.group}}"
    mode: '650'
    recurse: yes
  when: sasl_protocol == 'kerberos'

- name: Copy in Keytab File
  copy:
    src: "{{control_center_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{control_center_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  when: sasl_protocol == 'kerberos'
  notify:
    - restart control center

- name: Create Control Center Config
  template:
    src: control-center.properties.j2
    dest: "{{control_center.config_file}}"
    mode: 0640
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - restart control center

- name: Create Service Override Directory
  file:
    path: "{{control_center.systemd_override | dirname}}"
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{control_center.systemd_override}}"
    mode: 0640
    owner: "{{control_center.user}}"
    group: "{{control_center.group}}"
  notify:
    - reload systemd
    - restart control center

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart control center
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Control Center Service
  systemd:
    name: "{{control_center_service_name}}"
    enabled: yes
    state: started
