---
- name: Copy in MDS Public Pem File
  copy:
    src: "{{token_services_public_pem_file}}"
    dest: "{{rbac_enabled_public_pem_path}}"
    mode: '755'
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"

- name: Get Kafka Cluster Id
  include_tasks: ../../tasks/get_kafka_cluster_id.yml

- set_fact:
    certificate_args: ""
  when: not mds_ssl_enabled|bool

- set_fact:
    certificate_args: "--cacert {{control_center_ca_cert_path}}"
  when: mds_ssl_enabled|bool and not mds_ssl_mutual_auth_enabled|bool

- set_fact:
    certificate_args: "--cacert {{control_center_ca_cert_path}} --key {{control_center_key_path}} --cert {{control_center_cert_path}}"
  when: mds_ssl_enabled|bool and mds_ssl_mutual_auth_enabled|bool

- name: Grant role System Admin to Control Center user
  shell: |
    curl -X POST {{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{control_center_ldap_user}}/roles/SystemAdmin \
      -u "{{mds_super_user}}":"{{mds_super_user_password}}" -H "Content-Type: application/json" {{certificate_args}} \
      -d '{"clusters":{"kafka-cluster":"{{kafka_cluster_id}}"}}'
