### replicator-rhel
##
##  Tests replicator over plaintext on rhel
##
---
driver:
  name: docker
platforms:
  - name: kerberos1
    hostname: kerberos1.confluent
    groups:
      - kerberos_server
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: confluent-replicator1
    hostname: confluent_replicator1.confluent
    groups:
      - confluent_replicator
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
  - name: confluent-replicator2
    hostname: confluent_replicator2.confluent
    groups:
      - confluent_replicator
    image: geerlingguy/docker-centos7-ansible
    dockerfile: ../Dockerfile.j2
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    prepare: ../kerberos.yml
    converge: ../../../../all.yml
  inventory:
    group_vars:
      all:
        scenario_name: replicator-rhel-test

        kerberos:
          realm: realm.example.com
          kdc_hostname: kerberos1
          admin_hostname: kerberos1

        # ssl_enabled: true
        # sasl_protocol: plain

        # ssl_custom_certs: true
        # # Paths relative to all.yml
        # ssl_ca_cert_filepath: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/ca.crt"
        # ssl_signed_cert_filepath: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/{{inventory_hostname}}-ca1-signed.crt"
        # ssl_key_filepath: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/{{inventory_hostname}}-key.pem"
        # ssl_key_password: keypass

        # rbac_enabled: true

      #   kafka_broker_custom_log4j: false

      #   create_mds_certs: false
      #   token_services_public_pem_file: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/public.pem"
      #   token_services_private_pem_file: "roles/confluent.test/molecule/{{scenario_name}}/generated_ssl_files/tokenKeypair.pem"

      #   kafka_broker_custom_listeners:
      #     client_listener:
      #       name: CLIENT
      #       port: 9093

        # mds_super_user: mds
        # mds_super_user_password: password

        # kafka_broker_ldap_user: kafka_broker
        # kafka_broker_ldap_password: password

        # schema_registry_ldap_user: schema_registry
        # schema_registry_ldap_password: password

        # kafka_connect_ldap_user: kafka_connect
        # kafka_connect_ldap_password: password

        # ksql_ldap_user: ksql
        # ksql_ldap_password: password

        # kafka_rest_ldap_user: kafka_rest
        # kafka_rest_ldap_password: password

        # control_center_ldap_user: control_center
        # control_center_ldap_password: password

        # rbac_component_additional_system_admins:
        #   - user1

      # mds:
      #   kafka_broker_custom_properties:
      #     ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory
      #     ldap.com.sun.jndi.ldap.read.timeout: 3000
      #     ldap.java.naming.provider.url: ldaps://mds-ldap1:636
      #     ldap.java.naming.security.protocol: SSL
      #     ldap.ssl.truststore.location: /var/ssl/private/kafka_broker.truststore.jks
      #     ldap.ssl.truststore.password: confluenttruststorepass
      #     ldap.java.naming.security.principal: uid=mds,OU=rbac,DC=example,DC=com
      #     ldap.java.naming.security.credentials: password
      #     ldap.java.naming.security.authentication: simple
      #     ldap.user.search.base: OU=rbac,DC=example,DC=com
      #     ldap.group.search.base: OU=rbac,DC=example,DC=com
      #     ldap.user.name.attribute: uid
      #     ldap.user.memberof.attribute.pattern: CN=(.*),OU=rbac,DC=example,DC=com
      #     ldap.group.name.attribute: cn
      #     ldap.group.member.attribute.pattern: CN=(.*),OU=rbac,DC=example,DC=com
      #     ldap.user.object.class: account

      # cluster2:
      # #   external_mds_enabled: true

      # #   mds_broker_bootstrap_servers: mds-kafka-broker1:9093
      # #   mds_bootstrap_server_urls: https://mds-kafka-broker1:8090,https://mds-kafka-broker2:8090
      # #   mds_broker_listener:
      # #     ssl_enabled: true
      # #     ssl_mutual_auth_enabled: true
      # #     sasl_protocol: plain
      # cluster3:
      confluent_replicator:
        confluent_replicator_health_checks_enabled: false
        # jolokia_enabled: true
        jmxexporter_enabled: true
        kerberos_kafka_broker_primary: kafka
        confluent_replicator_white_list: test-replicator-source
        confluent_replicator_bootstrap_servers: kafka-broker1:9092
        confluent_replicator_kerberos_principal:  "zk/zookeeper1.confluent@{{kerberos.realm | upper}}"
        confluent_replicator_kerberos_keytab_path: "roles/confluent.test/molecule/{{scenario_name}}/keytabs/zookeeper-confluent-replicator.keytab"
        confluent_replicator_consumer_bootstrap_servers: mds-kafka-broker1:9092
        confluent_replicator_consumer_kerberos_principal:  "kafka-a/kafka-broker1.confluent@{{kerberos.realm | upper}}"
        confluent_replicator_consumer_kerberos_keytab_path: "roles/confluent.test/molecule/{{scenario_name}}/keytabs/kafka_broker-kafka-broker1.keytab"
      #   confluent_replicator_producer_bootstrap_servers: kafka-broker1:9092
      #   confluent_replicator_producer_kerberos_principal:  "schema_registry/{{inventory_hostname}}.confluent@{{kerberos.realm | upper}}"
      #   confluent_replicator_producer_kerberos_keytab_path: "roles/confluent.test/molecule/{{scenario_name}}/keytabs/kafka_broker-kafka-broker2.keytab"

      kerberos_server:
        realm_name: "{{ kerberos.realm | upper }}"

        keytab_output_directory: "{{scenario_name}}/keytabs"

        kerberos_principals:
          # Wish there was a better way to create this list, this will do for now
          - principal: "zk/zookeeper1.confluent@{{kerberos.realm | upper}}"
            keytab_path: "keytabs/zookeeper-confluent-replicator.keytab"

          - principal: "kafka-a/kafka-broker1.confluent@{{kerberos.realm | upper}}"
            keytab_path: "keytabs/kafka_broker-kafka-broker1.keytab"

          - principal: "kafka-a/kafka-broker2.confluent@{{kerberos.realm | upper}}"
            keytab_path: "keytabs/kafka_broker-kafka-broker2.keytab"


      # ldap_server:
      #   # Paths relative to scenario
      #   ldaps_enabled: true
      #   ldaps_custom_certs: true
      #   ssl_custom_certs: true
      #   ssl_ca_cert_filepath: "{{scenario_name}}/generated_ssl_files/ca.crt"
      #   ssl_signed_cert_filepath: "{{scenario_name}}/generated_ssl_files/{{inventory_hostname}}-ca1-signed.crt"
      #   ssl_key_filepath: "{{scenario_name}}/generated_ssl_files/{{inventory_hostname}}-key.pem"

      #   ldap_admin_password: ldppassword

      #   ldap_rbac_group: rbac
      #   ldap_dc: example
      #   ldap_dc_extension: com

      #   ldap_users:
      #     - username: "{{kafka_broker_ldap_user}}"
      #       password: "{{kafka_broker_ldap_password}}"
      #       uid: 9999
      #       guid: 99
      #     - username: "{{schema_registry_ldap_user}}"
      #       password: "{{schema_registry_ldap_password}}"
      #       uid: 9998
      #       guid: 98
      #     - username: "{{kafka_connect_ldap_user}}"
      #       password: "{{kafka_connect_ldap_password}}"
      #       uid: 9997
      #       guid: 97
      #     - username: "{{ksql_ldap_user}}"
      #       password: "{{ksql_ldap_password}}"
      #       uid: 9996
      #       guid: 96
      #     - username: "{{control_center_ldap_user}}"
      #       password: "{{control_center_ldap_password}}"
      #       uid: 9995
      #       guid: 95
      #     - username: "{{kafka_rest_ldap_user}}"
      #       password: "{{kafka_rest_ldap_password}}"
      #       uid: 9994
      #       guid: 94
      #     - username: "{{mds_super_user}}"
      #       password: "{{mds_super_user_password}}"
      #       uid: 9993
      #       guid: 93
      #     - username: user1
      #       password: user1p
      #       uid: 9992
      #       guid: 92

verifier:
  name: ansible
lint: |
  set -e
  yamllint -c ../../.yamllint ../..
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
