---
- name: Verify - Zookeeper User Change and custom logging path
  hosts: zookeeper1-kafka-broker1
  gather_facts: false
  tasks:
    - name: Set Zookeeper user to new user
      set_fact:
        zookeeper_user: zk-test-user

    - name: Set Zookeeper Group
      set_fact:
        zookeeper_group: confluent-custom

    - name: Create Zookeeper User
      user:
        name: "{{zookeeper_user}}"
        comment: "Zookeeper User"
        system: true
        group: "{{zookeeper_group}}"

    - name: Create Log Directory
      file:
        path: "{{zookeeper.log_path}}"
        state: directory
        group: "{{zookeeper_group}}"
        owner: "{{zookeeper_user}}"
        mode: 0770

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{zookeeper_service_name}}"
        state: restarted

    - import_role:
        name: confluent.zookeeper
        tasks_from: health_check.yml

    - name: Restart Service
      systemd:
        daemon_reload: true
        name: "{{kafka_broker_service_name}}"
        state: restarted

    - name: Wait for Under Replicated Partitions on Broker
      include_tasks: ../../../../tasks/wait_for_urp.yml
    
    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
        custom_path: /kafka/logs/zookeeper/

    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
          custom_path: /kafka/logs/kafka/
          
- name: Verify - Schema Registry custom user and custom group and custom logging directory
  hosts: schema_registry
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_user.yml
      vars:
        user: sr-cust+
        expected_value: sr-cust+

    - import_role:
        name: confluent.test
        tasks_from: check_group.yml
      vars:
        full_user: sr-custom
        group: sr-custom-group
    
    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
        custom_path: /kafka/logs/schemaregistry/

- name: Verify - Kafka Connect custom user and custom group and custom logging directory
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_user.yml
      vars:
        user: connect+
        expected_value: connect+

    - import_role:
        name: confluent.test
        tasks_from: check_group.yml
      vars:
        full_user: connect-custom
        group: connect-custom-group

    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
        custom_path: /kafka/logs/kafkaconnect/

- name: Verify - Rest Proxy custom user and custom group and custom logging directory
  hosts: kafka_rest
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_user.yml
      vars:
        user: rest-cu+
        expected_value: rest-cu+

    - import_role:
        name: confluent.test
        tasks_from: check_group.yml
      vars:
        full_user: rest-custom
        group: rest-custom-group

    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
        custom_path: /kafka/logs/kafkarest/

- name: Verify - KSQL custom user and custom Group
  hosts: ksql
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_user.yml
      vars:
        user: ksql-cu+
        expected_value: ksql-cu+

    - import_role:
        name: confluent.test
        tasks_from: check_group.yml
      vars:
        full_user: ksql-custom
        group: ksql-custom-group
        expected_value: ksql-custom-group

    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
          custom_path: /kafka/logs/ksql/

- name: Verify - C3 custom user and custom Group
  hosts: control_center
  gather_facts: no
  tasks:
    - import_role:
        name: confluent.test
        tasks_from: check_user.yml
      vars:
        user: c3-cust+
        expected_value: c3-cust+

    - import_role:
        name: confluent.test
        tasks_from: check_group.yml
      vars:
        full_user: c3-custom
        group: c3-custom-group
        expected_value: c3-custom-group

    - import_role:
        name: confluent.test
        tasks_from: check_directory.yml
      vars:
        custom_path: /kafka/logs/controlcenter/