---
driver:
  name: docker
platforms:
  - name: zookeeper1${CHANGE_ID}
    hostname: zookeeper1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - zookeeper
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: kafka-broker1${CHANGE_ID}
    hostname: kafka-broker1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - kafka_broker
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: schema-registry1${CHANGE_ID}
    hostname: schema-registry1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - schema_registry
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: kafka-rest1${CHANGE_ID}
    hostname: schema-kafka-rest1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - kafka_rest
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: kafka-connect1${CHANGE_ID}
    hostname: kafka-connect1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - kafka_connect
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: ksql1${CHANGE_ID}
    hostname: ksql1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - ksql
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    networks:
      - name: confluent${CHANGE_ID}
  - name: control-center1${CHANGE_ID}
    hostname: control-center1${CHANGE_ID}.confluent${CHANGE_ID}
    groups:
      - control_center
    image: geerlingguy/docker-centos7-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    published_ports:
      - "9021:9021"
    networks:
      - name: confluent${CHANGE_ID}
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    converge: ../../../../all.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
