- name: Install the Confluent KSQL Package
  apt:
    name: confluent-ksql
    update_cache: yes


- name: Install the Confluent Security Packages
  apt:
    name: confluent-security
    update_cache: yes

- name: Install the Confluent SERDE Packages
  apt:
    name: confluent-libserdes
    update_cache: yes
