- name: Install the Confluent ksql Package
  yum:
    name: confluent-ksql
    state: latest

- name: Install the Confluent Security Packages
  yum:
    name: confluent-security
    state: latest

- name: Install the Confluent SERDE Packages
  yum:
    name: confluent-libserdes
    state: latest
