---
- name: Delete SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: absent

- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Copy CA Cert to Host
  copy:
    src: "{{CA_cert_file_path}}"
    dest: "/var/ssl/private/generation/{{CA_cert}}"

- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -alias CARoot -import -file /var/ssl/private/generation/{{CA_cert}} \
      -storepass {{truststore_pass}} -keypass {{CA_pass}}

- name: Create Keystore with Self Signed Certs
  include_tasks: self_signed_keystore.yml
  #when: self_signed|bool

# - name: Delete SSL Certificate Generation Directory
#   file:
#     path: /var/ssl/private/generation
#     state: absent
#   when: delete_dir|bool
