---
- name: Copy CA Cert to Host
  copy:
    src: "{{ssl_ca_cert_filepath}}"
    dest: "/var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}}"

- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}}

- name: Copy Signed Host Cert to Host
  copy:
    src: "{{ssl_signed_cert_filepath}}"
    dest: /var/ssl/private/generation/signed.crt

- name: Copy Host Keystore to Host
  copy:
    src: "{{ssl_keystore_filepath}}"
    dest: /var/ssl/private/generation/keystore.jks

- name: Create Keystore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file /var/ssl/private/generation/{{ssl_ca_cert_filepath|basename}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_keypass}}

- name: Import the Host Certificate into the keystore
  shell: |
    keytool -noprompt -keystore {{keystore_path}} \
      -alias host \
      -import -file /var/ssl/private/generation/signed.crt \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_keypass}} \
      -keyalg RSA

- name: Import the keystore into the keystore (must be in pkcs12)
  shell: |
    keytool -importkeystore \
      -srcstorepass {{ssl_keystore_store_password}} \
      -srckeystore /var/ssl/private/generation/keystore.jks \
      -srcstoretype PKCS12 \
      -deststorepass {{keystore_storepass}} \
      -destkeystore {{keystore_path}}
