global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'kafka'
    static_configs:
    - targets:
      - 'vm1:8080'
      - 'vm2:8080'
      - 'vm3:8080'
      labels:
        env: 'dev'

  - job_name: 'zookeeper'
    static_configs:
    - targets:
      - 'vm1:8079'
      - 'vm2:8079'
      - 'vm3:8079'
      labels:
        env: 'dev'

  - job_name: 'connect'
    static_configs:
      - targets:
          - 'vm5:8077'
          - 'vm6:8077'
        labels:
          env: 'dev'
          cluster: 'cluster1'

  - job_name: 'ksql'
    static_configs:
      - targets:
          - 'vm5:8076'
          - 'vm6:8076'
        labels:
          env: 'dev'
          cluster: 'cluster1'

  - job_name: 'kafka-lag-exporter'
    static_configs:
      - targets:
        - 'kafka-lag-exporter:9999'
        labels:
           env: 'dev'
