---
- name: Install and Configure Kerberos
  include_role:
    name: confluent.kerberos
  when: kerberos_configure|bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{kafka_rest.group}}"
    mode: '650'
    recurse: yes

- name: Copy in Keytab File
  copy:
    src: "{{kafka_rest_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{kafka_rest_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - restart kafka-rest
