# Install Packages
- name: Install the Kafka Rest Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Kafka Rest Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: Create Kafka Rest Group
  group:
    name: "{{kafka_rest.group}}"

- name: Create Kafka Rest User
  user:
    name: "{{kafka_rest.user}}"
    comment: "Kafka REST User"
    system: yes
    group: "{{kafka_rest.group}}"

- import_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{kafka_rest_truststore_storepass}}"
    truststore_path: "{{kafka_rest_truststore_path}}"
    keystore_path: "{{kafka_rest_keystore_path}}"
    keystore_storepass: "{{kafka_rest_keystore_storepass}}"
    keystore_keypass: "{{kafka_rest_keystore_keypass}}"
  when: kafka_rest_ssl_enabled|bool or kafka_broker_listeners[kafka_rest_kafka_listener_name]['ssl_enabled'] | default(ssl_enabled) | bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{kafka_rest.group}}"
    mode: '650'
    recurse: yes
  when: kafka_broker_listeners[kafka_rest_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'

- name: Copy in Keytab File
  copy:
    src: "{{kafka_rest_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{kafka_rest_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: kafka_broker_listeners[kafka_rest_kafka_listener_name]['sasl_protocol'] | default(sasl_protocol) | normalize_sasl_protocol == 'GSSAPI'
  notify:
    - restart kafka-rest

- name: Get Kafka Cluster ID from Zookeeper
  delegate_to: "{{ groups['zookeeper'][0] }}"
  shell: |
    /bin/zookeeper-shell localhost:2181 get /cluster/id 2> /dev/null | grep version | jq -r .id
  register: cluster_id  
  when: rbac_enabled|bool 

- name: export certificate to pem format for MDS login to create user
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  shell: |
    openssl pkcs12 -in /var/ssl/private/kafka_broker.keystore.jks \
      -out /var/ssl/private/kafka_broker.keystore.pem \
      -passin pass:{{keystore_storepass}} -passout pass:{{keystore_storepass}}
  when: rbac_enabled|bool 

- name: Login to MDS to get Security Token
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl -u "{{rbac_mtls_broker_admin}}":"{{rbac_mtls_broker_admin_password}}" -s http://localhost:8090/security/1.0/authenticate 2> /dev/null | grep auth_token | jq -r .auth_token
  register: rbac_token 
  when: rbac_enabled|bool

- name: Grant role Security Admin to Schema Registry user
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_mtls_schema_registry_user}}/roles/SecurityAdmin -X POST -d '{ "clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
  when: rbac_enabled|bool 

- name: Grant schema registry ResourceOwner on the group that Schema Registry nodes use to coordinate across the cluster 
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_mtls_schema_registry_user}}/roles/ResourceOwner/bindings -X POST -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}, "resourcePatterns": [{"resourceType": "Group", "name": "schema-registry-{{groups['schema_registry'][0]}}-{{schema_registry_listener_port}}"}]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
  when: rbac_enabled|bool 

- name: Grant schema registry ResourceOwner on the kafka topic where schemas are stored
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl http://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{rbac_mtls_schema_registry_user}}/roles/ResourceOwner/bindings -X POST -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_schemas" }]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
  when: rbac_enabled|bool 

- name: Remove exported pem file for MDS login
  file:
     path: /var/ssl/private/kafka_broker_keystore.pem
     state: absent
  when: rbac_enabled|bool and ssl_enabled|bool 

- name: Create Kafka Rest Config
  template:
    src: kafka-rest.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - restart kafka-rest

- name: Create Logs Directory
  file:
    path: "{{kafka_rest.appender_log_path}}"
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
    mode: '764'
    recurse: yes

- name: Create Kafka Rest log4j Config
  template:
    src: kafka-rest_log4j.properties.j2
    dest: "{{kafka_rest.log4j_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - restart kafka-rest

- name: Create Service Override Directory
  file:
    path: "{{kafka_rest.systemd_override | dirname }}"
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{kafka_rest.systemd_override}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - reload systemd
    - restart kafka-rest

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart kafka-rest
  when: certs_updated|bool

- meta: flush_handlers

- name: Start Kafka Rest Service
  systemd:
    name: "{{kafka_rest_service_name}}"
    enabled: yes
    state: started
