# Install Packages
- name: Install the Kafka Rest Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "RedHat"

- name: Install the Kafka Rest Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
    update_cache: yes
  loop: "{{kafka_rest_packages}}"
  when: ansible_os_family == "Debian"

# Configure environment
- name: kafka-rest create group
  group:
    name: "{{kafka_rest.group}}"
- name: kafka-rest create user
  user:
    name: "{{kafka_rest.user}}"
    comment: "Kafka REST User"
    system: yes
    group: "{{kafka_rest.group}}"
- name: Change keytabs ownership
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{kafka_rest.group}}"
    mode: '650'
    recurse: yes
- name: kafka-rest create config
  template:
    src: kafka-rest.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_ssl.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "ssl"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_sasl_ssl.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_ssl_customcerts.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "ssl_customcerts"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_kerberos.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "kerberos"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_kerberos_ssl.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "kerberos_ssl"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_kerberos_ssl_customcerts.properties.j2
    dest: "{{kafka_rest.config_file}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  when: security_mode == "kerberos_ssl_customcerts"
  notify:
    - restart kafka-rest

- name: Create Service Override Directory
  file:
    path: "{{kafka_rest.systemd_override | dirname }}"
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
    state: directory
    mode: 0640

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{kafka_rest.systemd_override}}"
    mode: 0640
    owner: "{{kafka_rest.user}}"
    group: "{{kafka_rest.group}}"
  notify:
    - reload systemd
    - restart kafka-rest

- meta: flush_handlers

- name: Start Kafka Rest Service
  systemd:
    name: "{{kafka_rest_service_name}}"
    enabled: yes
    state: started
