---
- name: Restart Confluent Replicator Service
  systemd:
    daemon_reload: true
    name: "{{confluent_replicator_service_name}}"
    state: restarted

# - name: Health Check
#   include: health_check.yml
#   when:
#     - kafka_connect_health_checks_enabled|bool
#     - not ansible_check_mode