ksql_jaas_file: /etc/ksql/ksql-server_jaas.conf
ksql_jaas_java_arg: "-Djava.security.auth.login.config={{ksql_jaas_file}}"
ksql_jolokia_java_arg: "-javaagent:{{jolokia_jar_path}}=port={{ksql_jolokia_port}},host=0.0.0.0"
ksql_open_file_limit: "{{open_file_limit}}"
ksql_service_environment_overrides:
  KSQL_HEAP_OPTS: "-Xmx3g"
  KSQL_OPTS: "{{ ksql_jolokia_java_arg + ' ' + ksql_jaas_java_arg if security_mode in ['kerberos', 'kerberos_ssl', 'kerberos_ssl_customcerts'] else ksql_jolokia_java_arg }}"
ksql_service_overrides:
  LimitNOFILE: "{{ksql_open_file_limit}}"

ksql_streamsDataDir: /var/lib/kafka-streams

ksql:
  properties:
    application.id: ksql-server
    listeners: http://0.0.0.0:{{ksql_listener_port}}
    ssl.endpoint.identification.algorithm: ""
    ksql.streams.state.dir: "{{ksql_streamsDataDir}}"
