- name: debian apt-get update
  shell: apt-get -o Acquire::Check-Valid-Until=false update
- name: yum-clean-all
  command: yum clean all
  args:
    warn: no
- name: reload systemd
  systemd:
    daemon_reload: yes
