---
- name: Register if Keystore Exists
  stat:
    path: "{{keystore_path}}"
  register: keystore

- name: Register if Truststore Exists
  stat:
    path: "{{truststore_path}}"
  register: truststore

- name: Create Keystore and Truststore
  include_tasks: create_keystore_and_truststore.yml
  when: keystore.stat.exists == false or truststore.stat.exists == false or regenerate_keystore_and_truststore == true
