---
- name: Delete SSL Certificate Directory
  file:
    path: /var/ssl/private
    state: absent

- name: Create SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: directory
    mode: 0755

- name: Create Keystore with Self Signed Certs
  include_tasks: self_signed_keystore.yml
  when: self_signed|bool

- name: Create Keystore with Provided Certs
  include_tasks: provided_certs.yml
  when: security_mode in ['ssl_customcerts', 'kerberos_ssl_customcerts']

- set_fact:
    certs_updated: true

- name: Delete SSL Certificate Generation Directory
  file:
    path: /var/ssl/private/generation
    state: absent
