---
- name: Copy Host Truststore to Host
  copy:
    src: "{{ssl_truststore_filepath}}"
    dest: "{{truststore_path}}"

- name: Export CA Cert from Truststore
  shell: |
    openssl pkcs12 -in {{truststore_path}} \
      -out {{ca_cert_path}} \
      -passin pass:{{truststore_storepass}}

- name: Copy Host Keystore to Host
  copy:
    src: "{{ssl_keystore_filepath}}"
    dest: "{{keystore_path}}"

- name: Convert Keystore to Pem Format
  shell: |
    keytool -noprompt -importkeystore \
      -srckeystore {{keystore_path}} \
      -srcstorepass {{keystore_storepass}} \
      -srckeypass {{keystore_keypass}}
      -destkeystore /var/ssl/private/{{service_name}}.p12 \
      -deststoretype PKCS12 \
      -deststorepass {{keystore_storepass}} \
      -destkeypass {{keystore_storepass}}

- name: Export Certificate
  shell: |
    openssl pkcs12 -in /var/ssl/private/{{service_name}}.p12 \
      -nokeys -out {{cert_path}} \
      -passin pass:{{keystore_storepass}}

- name: Export Key
  shell: |
    openssl pkcs12 -in /var/ssl/private/{{service_name}}.p12 \
      -nodes -nocerts -out {{key_path}} \
      -passin pass:{{keystore_storepass}}
