---
- name: Copy MDS Private Key to Host
  copy:
    src: "{{rbac_mds_private_key_filepath}}"
    dest: "{{rbac_mds_private_key_path}}"

- name: Copy MDS Public Key to Host
  copy:
    src: "{{rbac_mds_public_key_filepath}}"
    dest: "{{rbac_mds_public_key_path}}"
