---
- name: Verify - kafka_connect
  hosts: kafka_connect1
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'group.id=connect_syslog' /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_connect
  hosts: kafka_connect2
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'group.id=connect_elastic' /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - ksql
  hosts: ksql1
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'ksql.service.id=ksql1_' /etc/ksql/ksql-server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - ksql
  hosts: ksql2
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'ksql.service.id=ksql2_' /etc/ksql/ksql-server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center
  gather_facts: no
  tasks:
    - name: Check line multi ksql line
      shell: |
        grep -Fq 'confluent.controlcenter.connect.ks1.ssl.truststore.location=/var/ssl/private/control_center.truststore.jks' /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

    - name: Check line multi connect line
      shell: |
        grep -Fq 'confluent.controlcenter.connect.connect-elastic.cluster=https://kafka-connect2:8083' /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
