---
- name: Install and configure OpenLDAP
  hosts: ldap_server
  tasks:
    - import_role:
        name: confluent.ldap

    # - name: Install OpenSSL and Rsync - RedHat
    #   yum:
    #     name: "{{item}}"
    #     state: present
    #   loop:
    #     - openssl
    #     - rsync
    #   when: ansible_os_family == "RedHat"
    #
    # - name: Create SSL Certificate Generation Directory
    #   file:
    #     path: /var/ssl/private/generation
    #     state: directory
    #     mode: 0755
    #   run_once: true
    #
    # - name: Create 2048-bit RSA Private key
    #   shell: |
    #     openssl genrsa \
    #       -out /var/ssl/private/generation/{{token_services_private_pem_file|basename}} 2048
    #   run_once: true
    #
    # - name: Extract Public key
    #   shell: |
    #     openssl rsa \
    #       -in /var/ssl/private/generation/{{token_services_private_pem_file|basename}} \
    #       -outform PEM -pubout \
    #       -out /var/ssl/private/generation/{{token_services_public_pem_file|basename}}
    #   run_once: true
    #
    # - name: Copy Generated SSL Files Back to Ansible Host
    #   synchronize:
    #     src: /var/ssl/private/generation/
    #     dest: generated_ssl_files
    #     mode: pull
    #   run_once: true
