---
- name: Verify - kafka_broker
  hosts: kafka_broker
  gather_facts: no
  tasks:
    - name: Check line in server.properties
      shell: |
        grep -Fq 'ldap.java.naming.provider.url=ldap://ldap1:389' /etc/kafka/server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - schema_registry
  hosts: schema_registry
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/schema-registry/schema-registry.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_rest
  hosts: kafka_rest
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/kafka-rest/kafka-rest.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

    - name: Get Connect Cluster Details
      uri:
        url: https://localhost:8083
        status_code: 200
        validate_certs: no
        url_username: kafka-connect1
        url_password: password
        force_basic_auth: true
      register: connect_cluster_query

    - set_fact:
        connect_cluster_json: "{{connect_cluster_query.json}}"

    - name: Set Kafka Cluster Id
      set_fact:
        kafka_cluster_id: "{{connect_cluster_json.kafka_cluster_id}}"

- name: Verify - ksql
  hosts: ksql
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/ksql/ksql-server.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0

- name: Verify - control_center
  hosts: control_center
  gather_facts: no
  tasks:
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/confluent-control-center/control-center-production.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
