---
- name: Verify - kafka_connect
  hosts: kafka_connect
  gather_facts: no
  tasks:
#     - name: Get kafka cluster id
#       uri:
#
#         curl https://kafka-connect1:8083 -u kafka-connect1:password -k
# {"version":"5.4.0-ce","commit":"ca78a82127cbef3a","kafka_cluster_id":"A2aHykA1Tv6ZdDQfGO4_3w"
    - name: Check line properties file
      shell: |
        grep -Fq 'public.key.path=/var/ssl/private/public.pem' /etc/kafka/connect-distributed.properties
      register: linecheck
      check_mode: no
      changed_when: no
      failed_when: linecheck.rc != 0
