---

- name: Install the kerberos packages
  yum:
    state: present
    name: "{{ kerberos.redhat_packages }}"
  #   name: "{{ item }}"
  # with_items: "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat"


- name: Install the kerberos packages
  apt:
    state: present
    name: "{{ kerberos.ubuntu_packages }}"
  # apt: name= "{{ item }}" state=present
  # with_items: "{{ ubuntu_packages }}"
  when: ansible_os_family == "Debian"

- name: Copy the client configuration file
  template: src=krb5.conf.j2 dest=/etc/krb5.conf

- name: copy Keytabs from ansible host to all hosts
  synchronize:
    src: "{{ keytab_source_dir }}"
    dest: "{{ kerberos.keytab_dir }}"
    mode: push
