---

- name: Install the kerberos packages
  yum:
    state: present
  with_items: "{{ redhat_packages }}"
  when: ansible_os_family == "RedHat"


- name: Install the kerberos packages
  apt: name={{ item }} state=present
  with_items: "{{ ubuntu_packages }}"
  when: ansible_os_family == "Debian"

- name: Copy the client configuration file
  template: src=krb5.conf.j2 dest=/etc/krb5.conf
