---
- name: Find Property in File
  shell: "grep '^{{property}}=' {{file_path}}"
  register: grep
  changed_when: false


# - set_fact:
#     value: "{{ grep.stdout | regex_replace('^[a-z.]*=(.*)$', '\\1') }}"
#
#
# - debug: var=value




- name: Assert property set as expected
  assert:
    that:
      - expected_value == grep.stdout | regex_replace('^[a-z.]*=(.*)$', '\\1')
      # - expected_value == grep.stdout.split('=')[1]
    fail_msg: "Property: {{property}} set to {{ grep.stdout | regex_replace('^[a-z.]*=(.*)$', '\\1') }} not {{expected_value}}"
    quiet: true
