---
- name: Get Kafka Cluster ID from Embedded Rest Proxy
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/kafka/v3/clusters"
    method: GET
    validate_certs: false
    body_format: json
    return_content: true
    status_code: 200
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    force_basic_auth: true
  register: cluster_id_query

- name: Parse Kafka Cluster ID from json query
  set_fact:
    kafka_cluster_id: "{{ cluster_id_query.json.data[0].cluster_id }}"

- name: Retrieve Cluster Registry details
  uri:
    url: "{{mds_http_protocol}}://{{ groups['kafka_broker'][0] }}:{{mds_port}}/security/1.0/registry/clusters"
    method: GET
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    status_code: 200
  register: cluster_name_query

- set_fact:
    cluster_name_query_json: "{{ cluster_name_query.json }}"

- name: Assert Broker Cluster ID as expected
  assert:
    that:
      - broker_id == "{{cluster_name_query_json | json_query('[0].clusterName')}}"
    fail_msg: "Broker ID set to {{cluster_name_query_json | json_query('[0].clusterName')}} not {{broker_id}}"
    quiet: true

- name: Assert Kafka Connect Cluster ID as expected
  assert:
    that:
      - connect_id == "{{cluster_name_query_json | json_query('[1].clusterName')}}"
    fail_msg: "Connect Cluster ID set to {{cluster_name_query_json | json_query('[1].clusterName')}} not {{connect_id}}"
    quiet: true

- name: Assert KSQL Cluster ID as expected
  assert:
    that:
      - ksql_id == "{{cluster_name_query_json | json_query('[2].clusterName')}}"
    fail_msg: "KSQL Cluster ID set to {{cluster_name_query_json | json_query('[2].clusterName')}} not {{ksql_id}}"
    quiet: true

- name: Assert Schema Registry Cluster ID as expected
  assert:
    that:
      - sr_id == "{{cluster_name_query_json | json_query('[3].clusterName')}}"
    fail_msg: "Schema Registry Cluster ID set to {{cluster_name_query_json | json_query('[3].clusterName')}} not {{sr_id}}"
    quiet: true
