---
- name: Install and Configure Kerberos
  include_role:
    name: confluent.kerberos
  when: kerberos_configure|bool

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{schema_registry.group}}"
    mode: '650'
    recurse: yes

- name: Copy in Keytab File
  copy:
    src: "{{schema_registry_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{schema_registry_kerberos_keytab_path | basename}}"
    mode: '600'
    owner: "{{schema_registry.user}}"
    group: "{{schema_registry.group}}"
  notify:
    - restart schema-registry
