---
- name: Grant Schema Registry user the role SecurityAdmin on the Schema Registry cluster.
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/ca.crt --key /var/ssl/private/schema_registry.key --cert /var/ssl/private/schema_registry.crt \
      -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/SecurityAdmin \
      -H "accept: application/json" -H "Authorization: Bearer {{rbac_token}}" -H "Content-Type: application/json" \
      -d '{"clusters":{"kafka-cluster": "{{cluster_id}}", "schema-registry-cluster": "{{schema_registry.properties['schema.registry.group.id']}}"}}"'

- name: Grant Schema Registry user ResourceOwner on the group that Schema Registry nodes use to coordinate across the cluster
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/ca.crt --key /var/ssl/private/schema_registry.key --cert /var/ssl/private/schema_registry.crt \
      -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings \
      -H "accept: application/json" -H "Authorization: Bearer {{rbac_token}}" -H "Content-Type: application/json" \
      -d '{"scope":{"clusters":{"kafka-cluster": "{{cluster_id}}"}}, "resourcePatterns":[{"resourceType":"Group","name": "{{schema_registry.properties['schema.registry.group.id']}}","patternType":"LITERAL"}]}'

- name: Grant Schema Registry user ResourceOwner on the kafka topic where schemas are stored
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/ca.crt --key /var/ssl/private/schema_registry.key --cert /var/ssl/private/schema_registry.crt \
      -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings \
      -H "accept: application/json" -H "Authorization: Bearer {{rbac_token}}"  -H "Content-Type: application/json" \
      -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "{{schema_registry.properties['kafkastore.topic']}}" }]}'
