

- name: Grant role Security Admin to Schema Registry user when using self signed certificates
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/SecurityAdmin -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"clusters":{"kafka-cluster":"{{cluster_id}}","schema-registry-cluster":"schema-registry"}}"'
 
- name: Grant schema registry ResourceOwner on the group that Schema Registry nodes use to coordinate across the cluster when using self signed certificates
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster": "{{cluster_id}}"}}, "resourcePatterns":[{"resourceType":"Group","name": "schema-registry","patternType":"LITERAL"}]}' 

- name: Grant schema registry ResourceOwner on the kafka topic where schemas are stored when using self signed certificates
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --insecure --key /var/ssl/private/kafka_broker.keystore.pem:{{kafka_broker_keystore_storepass}} https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{inventory_hostname}}/roles/ResourceOwner/bindings -X POST -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_schemas" }]}' -H "Content-Type: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"
 
