

- name: Grant role Security Admin to Schema Registry user
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/SecurityAdmin -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"clusters":{"kafka-cluster": "{{cluster_id.stdout}}", "schema-registry-cluster": "schema-registry"}}"'
 
- name: Grant schema registry ResourceOwner on the group that Schema Registry nodes use to coordinate across the cluster
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}" -H "Content-Type: application/json" -d '{"scope":{"clusters":{"kafka-cluster": "{{cluster_id.stdout}}"}}, "resourcePatterns":[{"resourceType":"Group","name": "schema-registry","patternType":"LITERAL"}]}'
 
- name: Grant schema registry ResourceOwner on the kafka topic where schemas are stored
  delegate_to: "{{ groups['kafka_broker'][0] }}"
  delegate_facts: true
  shell: |
    curl --cacert /var/ssl/private/kafka_broker.truststore.pem --key /var/ssl/private/key.pem --cert /var/ssl/private/cert.pem -X POST https://{{ groups['kafka_broker'][0] }}:8090/security/1.0/principals/User:{{principal_name}}/roles/ResourceOwner/bindings -H "accept: application/json" -H "Authorization: Bearer {{rbac_token.stdout}}"  -H "Content-Type: application/json" -d '{ "scope": {"clusters": {"kafka-cluster":"{{cluster_id.stdout}}"}}, "resourcePatterns": [{"resourceType": "Topic", "name": "_schemas" }]}'
