---
- name: Get Kafka Cluster Id
  include_tasks: ../../tasks/rbac_setup.yml
  vars:
    copy_certs: false

- name: Register Schema Registry Cluster
  uri:
    url: "{{mds_bootstrap_server_urls.split(',')[0]}}/security/1.0/registry/clusters"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    # For audit logs, must register the oauth listener which will be the "internal" listener
    body: >
      [
          {
              "clusterName": "{{cluster_registry_cluster_name}}",
              "scope": {
                  "clusters": {
                      "kafka-cluster": "{{kafka_cluster_id}}",
                      "schema-registry-cluster": "{{schema_registry_final_properties['schema.registry.group.id']}}"
                  }
              },
              "hosts": [ {% for host in groups['schema_registry'] %}{% if loop.index > 1%},{% endif %}{ "host": "{{host}}", "port": {{schema_registry_listener_port}} }{% endfor %}
              ],
              "protocol": "{{schema_registry_http_protocol}}"
          }
      ]
    status_code: 204
  run_once: true
  register: output
