---
- name: Check if Connect Service Running
  shell: "systemctl show -p SubState {{schema_registry_service_name}}"
  changed_when: false
  register: substate

- name: Parallel Restart
  include: restart.yml
  when: substate.stdout != 'SubState=running'

# TODO There was an issue with bringing them both up at the same time, topic creation problem. Probably want to do serial all the time

# All connect hosts iterate over the list of connect hosts, each seeing the list in the same order
# At one given loop entry, only one host will have its inventory_hostname match  the entry in the loop
# restart.yml tasks will only run for that host ON that host
- name: Serial Restart
  include: restart.yml
  delegate_to: "{{ item }}"
  loop: "{{ groups['schema_registry'] }}"
  when:
    - "hostvars[item].inventory_hostname == inventory_hostname"
    - substate.stdout == 'SubState=running'
