# JVM Installation and Repo Setup
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

- name: Create Jolokia directory
  file:
    path: /opt/jolokia
    state: directory
    mode: 0755

- name: Download Jolokia Jar
  get_url:
    url: "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{{jolokia_version}}/jolokia-jvm-{{jolokia_version}}-agent.jar"
    dest: "{{ jolokia_jar_path }}"

- name: Set sasl_protocol Variable
  set_fact:
    sasl_protocol: kerberos
  when:
    - security_mode in ['kerberos', 'kerberos_ssl', 'kerberos_ssl_customcerts']

- name: Set sasl_protocol Variable
  set_fact:
    sasl_protocol: none
  when:
    - security_mode in ['plaintext', 'ssl', 'ssl_customcerts']

- name: Set sasl_protocol Variable
  set_fact:
    sasl_protocol: 'plain'
  when:
    - security_mode in ['sasl_ssl']

- name: Set ssl_enabled Variable
  set_fact:
    ssl_enabled: true
  when:
    - security_mode in ['ssl', 'sasl_ssl', 'ssl_customcerts', 'kerberos_ssl', 'kerberos_ssl_customcerts']

- name: Set ssl_enabled Variable
  set_fact:
    ssl_enabled: "{{ false if security_mode in ['plaintext', 'kerberos'] else true }}"

- name: Set ssl_enabled Variable
  set_fact:
    customcerts: "{{ true if security_mode in ['ssl_customcerts', 'kerberos_ssl_customcerts'] else false }}"

- name: Set SASL Protocol
  set_fact:
    sasl_protocol: none
  when:
    - security_mode in ['plaintext', 'ssl', 'ssl_customcerts']

- name: Set SASL Protocol
  set_fact:
    sasl_protocol: 'plain'
  when:
    - security_mode in ['sasl_ssl']

- name: Set Broker Protocol Variable
  set_fact:
    kafka_broker_protocol: SASL_PLAINTEXT
  when:
    - not cp_ssl_enabled|bool
    - cp_sasl_protocol == 'kerberos' or cp_sasl_protocol == 'plain'

- name: Set Broker Protocol Variable
  set_fact:
    kafka_broker_protocol: SSL
  when:
    - cp_ssl_enabled|bool
    - cp_sasl_protocol == 'none'

- name: Set Broker Protocol Variable
  set_fact:
    kafka_broker_protocol: PLAINTEXT
  when:
    - not cp_ssl_enabled|bool
    - cp_sasl_protocol == 'none'

- name: print PROTOCOL!!!!!!!
  debug: var=kafka_broker_protocol
