# JVM Installation
- import_tasks: redhatjvm.yml
  when: ansible_os_family == "RedHat"
- import_tasks: ubuntujvm.yml
  when: ansible_distribution == "Ubuntu"
- import_tasks: debianjvm.yml
  when: ansible_distribution == 'Debian'
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

# Package Installation
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: ssl_certs.yml
  when: security_mode == "ssl" or security_mode == "sasl_ssl" or security_mode == "kerberos_ssl" or security_mode == "ssl_customcerts" or security_mode == "kerberos_ssl_customcerts"

