# JVM Installation and Repo Setup
- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'

- name: Create Jolokia directory
  file:
    path: /opt/jolokia
    state: directory
    mode: 0755

- name: Download Jolokia Jar
  get_url:
    url: "http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/{{jolokia_version}}/jolokia-jvm-{{jolokia_version}}-agent.jar"
    dest: "{{ jolokia_jar_path }}"
