- name: Install the Confluent Platform
  apt:
    name: confluent-kafka
    update_cache: yes
  when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts" or security_mode == "plaintext" or security_mode == "ssl" or security_mode == "ssl_customcerts" or security_mode == "sasl_ssl"


- name: Install the Confluent Security Package
  apt:
    name: confluent-security
    update_cache: yes
