---
- name: Export Zookeeper Error Logs
  shell: "journalctl -u {{zookeeper_service_name}} --since -10m > /tmp/{{zookeeper_service_name}}.log"

- name: Fetch Files for Investigation
  fetch:
    src: "{{item}}"
    dest: "error_files/{{inventory_hostname}}-{{item|basename}}"
    flat: true
    fail_on_missing: false
  loop:
    - "{{zookeeper.config_file}}"
    - "/tmp/{{zookeeper_service_name}}.log"

- name: Fail Zookeeper Installation
  fail:
    msg: Zookeeper health check failed. Review log and property files in error_files/ directory
