---
- name: Install and Configure Kerberos
  include_role:
    name: confluent.kerberos
  when: kerberos_configure|bool"

- name: Create Keytabs Directory
  file:
    path: "{{kerberos.keytab_dir}}"
    group: "{{zookeeper.group}}"
    mode: '650'
    recurse: yes

- name: Copy in Keytab File
  copy:
    src: "{{zookeeper_kerberos_keytab_path}}"
    dest: "{{kerberos.keytab_dir}}/{{zookeeper_kerberos_keytab_path | basename}}"
    owner: "{{zookeeper.user}}"
    group: "{{zookeeper.group}}"
    mode: '600'
  notify:
    - restart zookeeper
