- name: Install the Confluent Kafka Package
  yum:
    name: confluent-kafka
    state: latest
  when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts" or security_mode == "plaintext" or security_mode == "ssl" or security_mode == "ssl_customcerts" or security_mode == "sasl_ssl"


- name: Install the Confluent Security Packages
  yum:
    name: confluent-security
    state: latest
