- name: Install the Confluent Platform
  yum:
    name: "{{confluent.package_name}}"
    state: latest

- name: Install the Confluent Security Packages
  yum:
    name: confluent-security
    state: latest
