---
- name: Set security_protocol Variable
  set_fact:
    security_protocol: SASL_SSL
  when:
    - ssl_enabled|bool
    - sasl_protocol == 'kerberos' or sasl_protocol == 'plain'

- name: Set security_protocol Variable
  set_fact:
    security_protocol: SASL_PLAINTEXT
  when:
    - not ssl_enabled|bool
    - sasl_protocol == 'kerberos' or sasl_protocol == 'plain'

- name: Set security_protocol Variable
  set_fact:
    security_protocol: SSL
  when:
    - ssl_enabled|bool
    - sasl_protocol == 'none'

- name: Set security_protocol Variable
  set_fact:
    security_protocol: PLAINTEXT
  when:
    - not ssl_enabled|bool
    - sasl_protocol == 'none'
