---
- name: Set kafka_broker_security_protocol Variable
  set_fact:
    kafka_broker_security_protocol: SASL_SSL
  when:
    - kafka_broker_ssl_enabled|bool
    - sasl_protocol == 'kerberos' or sasl_protocol == 'plain'

- name: Set kafka_broker_security_protocol Variable
  set_fact:
    kafka_broker_security_protocol: SASL_PLAINTEXT
  when:
    - not kafka_broker_ssl_enabled|bool
    - sasl_protocol == 'kerberos' or sasl_protocol == 'plain'

- name: Set kafka_broker_security_protocol Variable
  set_fact:
    kafka_broker_security_protocol: SSL
  when:
    - kafka_broker_ssl_enabled|bool
    - sasl_protocol == 'none'

- name: Set kafka_broker_security_protocol Variable
  set_fact:
    kafka_broker_security_protocol: PLAINTEXT
  when:
    - not kafka_broker_ssl_enabled|bool
    - sasl_protocol == 'none'
