- name: Install the Confluent Kafka Package
  apt:
    name: confluent-kafka-2.12
    update_cache: yes
  when: security_mode == "kerberos" or security_mode == "kerberos_ssl" or security_mode == "kerberos_ssl_customcerts" or security_mode == "plaintext" or security_mode == "ssl" or security_mode == "ssl_customcerts" or security_mode == "sasl_ssl"


- name: Install the Confluent Security Packages
  apt:
    name: confluent-security
    update_cache: yes

- name: Install the Confluent SERDE Packages
  apt:
    name: confluent-libserdes
    update_cache: yes

- name: Install the Confluent Rebalancer Packages
  apt:
    name: confluent-rebalancer
    update_cache: yes

- name: Install the Confluent Support Packages
  apt:
    name: confluent-support-metrics
    update_cache: yes

- name: Install the Confluent Avro Packages
  apt:
    name: avro
    update_cache: yes

